### ISSUE TITLE
When screen configuration change, i3lock is hidden

### ISSUE THREAD

**Issue by vincentbernat** [i3/i3lock#101]
Hey!

When I unplug or plug a screen, xrandr reconfigures the screens. If i3lock was running, it still has the grab on the keyboard and the mouse but it is hidden in the background. I am using awesome as a window manager (it restarts when there is a configuration change), so I am unsure if the problem is in awesome or i3lock.

I don't know if i3lock could try to stay on top or if it should listen to RANDR events.

**Comment by Airblader** [comment]
> I don't know if i3lock could try to stay on top or if it should listen to RANDR events.

It does both.

**Comment by vincentbernat** [comment]
OK, so maybe the problem is in awesome and I should just ensure i3lock is on top on start/restart.

**Comment by Airblader** [comment]
I'm pretty sure both applications generally behave correctly in this case, but obviously *something* isn't working. You could run i3lock under xtrace and then we can see what i3lock is doing when it goes to the background.

**Comment by vincentbernat** [comment]
OK, I'll do that and report here.

**Comment by stapelberg** [comment]
Actually, i3lock doesn’t listen to RANDR events, it only uses Xinerama. This will be addressed as part of issue #159.

**Comment by stapelberg** [comment]
Optimistically closing this under the assumption that c311d1c5a3e555ebac575de45f635c326fce5822 fixes the issue. Please re-open if it doesn’t.
