### ISSUE TITLE
Enter on C-m

### ISSUE THREAD

**Issue by nico202** [i3/i3lock#102]
Hi, I'm used to insert Enter with C-m (Control + m) like in emacs/bash, is it possible to enable this on i3lock?
Thanks, Nicolò

**Comment by stapelberg** [comment]
We already have C-j, so adding C-m should be just a matter of adding one constant here: https://github.com/i3/i3lock/blob/master/i3lock.c#L388

Can you send a pull request?

**Comment by nico202** [comment]
@stapelberg thanks, let me know if it is ok
