### ISSUE TITLE
How can I relogin immediately and remove "verifying" and "wrong"

### ISSUE THREAD

**Issue by Yekutiel** [i3/i3lock#104]
I like i3lock. Thanks to the dev(s) for creating and supporting it.

When I type in an incorrect password into i3lock I would like to immediately be able type in a new password. Specifically, I would prefer not to wait for "verifying" and "wrong." Actually, I don't want to see them at all. If I have failed logged in, it will be immediately obvious to me.

Below are two current scripts I use (which as I am sure you can easily discern, circumvent the problem of i3lock temporarily showing my actual desktop when I attempt to unlock my screen or wake up my computer from suspend/sleep mode).

#!/bin/sh
viewnior --fullscreen '/home/y/Images/My i3lock image' &
sleep 3s &&
i3lock -d -I3  -i '/home/y/Images/My i3lock image.png' -p default -n

*******************

#!/bin/sh
viewnior --fullscreen '/home/y/Images/My i3lock image.png' &
sleep 3s &&
dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.Suspend" boolean:true && i3lock -d -I3  -i '/home/y/Images/My i3lock image.png' -p default -n

**Comment by Airblader** [comment]
The delay comes from Pam and is a security feature. You can remove it in your Pam configuration, but you will make your machine more vulnerable doing so. 

http://unix.stackexchange.com/questions/2126/why-is-there-a-big-delay-after-entering-a-wrong-password

**Comment by Yekutiel** [comment]
Thanks. I followed your link to come up with a simple answer.

To decrease the delay down from three seconds to one I second I edited /etc/pam.d/login in as follows.

I changed:
auth       optional   pam_faildelay.so  delay=3000000
to
auth       optional   pam_faildelay.so  delay=1000000

Aside from a few thousand dollars of my money which immediately went missing from my checking account, apparently to some bank account belonging to "WeWillHackU"in a small town in the Ukraine, I have not noticed any other ill effects... yet.

On a serious note, Linux FOSS developers are typically so far out of touch with what ordinary users need it's absurd.

It's not all or nothing guys. There are gray areas in Linux and in life. Do you have 10 locks on your front door, a moat filled with water and alligators, and a draw bridge to secure your residence? No? Really. Hmmm. I wonder why not.

A three second delay for an ordinary is ridiculous. One second is reasonable. Wake up and smell the coffee FOSS developers. You make yourselves the butt of derisive jokes for a good reason: you are so self-centered that you ignore reasonable requests of ordinary users.

I realize you were probably teased and bullied as a child and have an irrational fear of being harmed by others. Try to work on yourselves and stop making us chase our tails around in a circle due to your paranoia.

**Comment by Airblader** [comment]
I'm not sure why you are switching to to this kind of verbal attack, but I'm not going to address it and lock this issue instead.
