### ISSUE TITLE
i3lock as a systemd service

### ISSUE THREAD

**Issue by mvalkon** [i3/i3lock#109]
I'm not sure if this is a bug in i3lock, or a bug somewhere else but since I can't really find anything. I'll report here, let's close this if it's clearly not a bug in i3lock.

I'm running on ubuntu 16.10, kernel 4.8.0-32-generic. I'm trying to configure i3lock to start before my laptop suspends, so that the screen is locked when I open the lid. I have the following systemd service:
```
→ cat /etc/systemd/system/i3lock.service 
[Unit]
Description=Lock screen before suspend
Before=sleep.target

[Service]
User=%I
Type=forking
Environment=DISPLAY=:0
ExecStart=/usr/bin/i3lock -c 000000
ExecStartPost=/bin/sleep 1

[Install]
WantedBy=suspend.target
```

Trying to start i3lock service results in the following error:
```
→ sudo systemctl start i3lock
Job for i3lock.service failed because the control process exited with error code.
See "systemctl status i3lock.service" and "journalctl -xe" for details.

→ systemctl status i3lock.service
● i3lock.service - Lock screen before suspend
   Loaded: loaded (/etc/systemd/system/i3lock.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2017-01-04 15:39:20 EET; 4s ago
  Process: 20097 ExecStart=/usr/bin/i3lock -c 000000 (code=exited, status=1/FAILURE)

Jan 04 15:39:20 slartibartfast systemd[1]: Starting Lock screen before suspend...
Jan 04 15:39:20 slartibartfast i3lock[20097]: No protocol specified
Jan 04 15:39:20 slartibartfast i3lock[20097]: i3lock: Could not connect to X11, maybe you need to set DISPLAY?
Jan 04 15:39:20 slartibartfast systemd[1]: i3lock.service: Control process exited, code=exited status=1
Jan 04 15:39:20 slartibartfast systemd[1]: Failed to start Lock screen before suspend.
Jan 04 15:39:20 slartibartfast systemd[1]: i3lock.service: Unit entered failed state.
Jan 04 15:39:20 slartibartfast systemd[1]: i3lock.service: Failed with result 'exit-code'.
```

I've verified that the `DISPLAY=:0` is correct by echoing the environment variable in the `ExecStart` directive. Is this a bug in i3lock, or a bug somewhere in xorg, systemd or ubuntu?

i3lock version, installed via `apt`. Running `i3lock -c 000000` as such works fine.
```
→ i3lock --version
i3lock: version 2.8 (2016-06-04) © 2010 Michael Stapelberg
```

**Comment by Airblader** [comment]
I also use systemd with i3lock and my unit file looks *almost* exactly the same. The only real difference is that I use

````
Type=simple
````

and call i3lock with `-n` (non-forking). I feel that this shouldn't make a difference, but why not at least see if it does? :-)

**Comment by mvalkon** [comment]
@Airblader thanks for the suggestion! Unfortunately the error is still there.

**Comment by Airblader** [comment]
We just have to look one line above:

````
Jan 04 15:39:20 slartibartfast i3lock[20097]: No protocol specified
````

That's the problem. You should be able to google that error message together with "xcb" or "xlib" to find the solution, probably some `xhost` call. For example my system always runs

````
xhost +local:root
````

So a quick check would be for you to run that, too, and then start the service again.

**Comment by mvalkon** [comment]
@Airblader that works perfectly. I only have to change the `User` field for myself, since otherwise it won't accept my password. Thanks for helping :)

**Comment by Airblader** [comment]
@mvalkon I guess I wasn't looking closely enough when checking out my own unit file. I actually have

````
User=%I
````

and then use `systemctl enable suspend@ingo.service` wherein `ingo` is my username. :-) The service file itself, of course, is then called `suspend@.service` as per convention.

**Comment by nixpulvis** [comment]
Thanks @Airblader was having a problem and it turned out to be missing the `--nofork` flag. :tada:
