### ISSUE TITLE
Chrome extension crash notification shown on-top of lockscreen.

### ISSUE THREAD

**Issue by wjdp** [i3/i3lock#111]
Just had a Chrome extension crash notification (rectangular floating window in bottom right of leftmost monitor) present on-top of the lockscreen when waking computer. Not the most privacy sensitive information but should expect these to fall behind.

**Comment by Airblader** [comment]
Are you using a compositor?

**Comment by Airblader** [comment]
Asking because I'm pretty sure this duplicates #22, which will be fixed by #96. You can give the patch there a try and report back!

**Comment by wjdp** [comment]
I am (compton), sorry haven't the time to test the patch but am 99% sure this is a dupe of #22. Apologies should have spotted that! Thanks.
