### ISSUE TITLE
i3lock fails within a second if mouse cursor is grabbed/occupied

### ISSUE THREAD

**Issue by GSI** [i3/i3lock#115]
Since tools like **unclutter** grab the mouse cursor, **i3lock** will fail. The bigger problem is that it doesn't fail directly - it shows the lock screen for a second and then, when you already left the workplace, your session is unlocked.

I work around the issue using the following function:

```
lock_screen () {
        DISPLAY_GEOMETRY=$(xdotool getdisplaygeometry | sed 's# #x#g')

        # NOTE mouse is moved as the lock operation otherwise fails:
        xdotool mousemove 0 0 && xdotool mousemove --polar 0 0 &&
                i3lock -bd
}
```

**However** this doesn't liberate the cursor in case tools like **xkill** occupy it.

Is there any reliable - and thus secure - way to handle such situations?

Why does i3lock even care about a mouse cursor? Can this "dependency" be removed?

**Comment by Airblader** [comment]
> The bigger problem is that it doesn't fail directly - it shows the lock screen for a second and then, when you already left the workplace, your session is unlocked

This isn't quite true anymore, see #88 and #99. That's really all we can do due to how X works. Given that this duplicates a few issues and we've addressed it now, I'm closing this. 

By the way, I've written unclutter-xfixes a little while ago. It's unclutter, but won't suffer from these problems.

**Comment by GSI** [comment]
I just tried the most recent i3lock version from git. It delays even more before it's becomes obvious that locking failed.

Does X provide no manner to check if mouse is occupied/available?
At best we could find out the PID that it blocking it (and kill the according process).

**Comment by Airblader** [comment]
> Does X provide no manner to check if mouse is occupied/available?

No, you just notice that it doesn't work.

> and kill the according process

We most certainly do not want to kill other processes. What if it's unsaved hours of work that you'd be destroying?

> I just tried the most recent i3lock version from git. It delays even more before it's becomes obvious that locking failed.

How do you start i3lock? You should see a message that locking is in progress (as you can see in the referenced PRs). Of course this assumes you actually display the unlock indicator.

**Comment by GSI** [comment]
> We most certainly do not want to kill other processes. What if it's unsaved hours of work that you'd be destroying?

I'd certainly prefer loosing hours of work over loosing years of work.

Of course that would be an optional switch in i3lock or even just something in a wrapper script.

Like even if i3lock just gave the PID as exit code, the situation could be handled according to user preference.


> How do you start i3lock?

Right now I tried with just `i3lock` on the command line. I get a white screen ... and then after a little while (almost a second) it says "locking in progress" for a split second and immediately that it failed.

**Comment by Airblader** [comment]
> I'd certainly prefer loosing hours of work over loosing years of work.

No, we definitely are not going to start killing other processes. Not even as an optional switch. If you want to do that in a wrapper script at your own risk, go ahead. But we cannot give the PID as the return code because those are two different things.

If you want to go such extreme measures anyway, you could write a wrapper script that checks if i3lock exited with a non-zero return code and forcefully shuts down the machine in that case (or at least logs out the user).

**Comment by GSI** [comment]
I can relate to your points.

I'll see if I can find a reasonable way to check if the mouse is available and do so before starting i3lock. (There must be some way since other lockers appear to handle it.)

**Comment by GSI** [comment]
Note: I just ran `xkill`. Then, while active, I triad to run a second instance which failed in an instant. Could i3lock do these checks this early too?

**Comment by Airblader** [comment]
i3lock *does* do this as early. But i3lock tries to grab a few hundred times (as recommended in the specs) and only displays a message after 250ms to avoid flickering for the vast majority of cases.
