### ISSUE TITLE
make redrawing the screen optional when no unlock visual is used

### ISSUE THREAD

**Issue by phavx** [i3/i3lock#12]
Former discussion here: https://faq.i3wm.org/question/5839/i3lock-how-to-disable-redraw/

start of the idea/problem here: http://redd.it/328e18

If you read this threads, you'll see I'm drawing some status information onto i3locks window with conky. The unlock indicator is disabled, so in theory there should be no need for a screen redraw (at least I see no technical need for this). As a result of redrawing the screen, my conky vanishes and reappers on every keypress (which looks strange and ugly) - happens with conky no matter if I used double buffer or not.

Therefor, I'd like to request an option to disable the redraw. Thanks.

**Comment by stapelberg** [comment]
The `unlock_indicator` option that we already have should be used for this. Please send a pull request in which the `redraw_screen()` calls on key presses are skipped if `unlock_indicator` is disabled. It’s better if you do it because then you know whether it works.

**Comment by Airblader** [comment]
@phavx Can you please try this patch?

http://pastebin.com/0vLwEgpU

**Comment by phavx** [comment]
@Airblader tried your patch against a fresh clone of i3lock, applies without warnings and works for me. Thank you :)

Still getting this, don't know if it's because I'm not running a compositor or something else, but the patch works for me:

X Error of failed request:  BadDamage (invalid Damage parameter)
  Major opcode of failed request:  142 (DAMAGE)
  Minor opcode of failed request:  3 (XDamageSubtract)
  Serial number of failed request:  67
  Current serial number in output stream:  68

**Comment by Airblader** [comment]
@stapelberg I'm getting the same error. I don't really know anything about the Damage extension. Is this normal?

I'll send a PR for the patch. Since i3lock releases are rare, I'd suggest you just go with the patch.
