### ISSUE TITLE
polybar and powerlines overriding i3lock

### ISSUE THREAD

**Issue by eoli3n** [i3/i3lock#121]
![alt tag](https://ptpb.pw/qViw.png)

This is ``i3lock`` without any argument. When i start i3lock, some areas overrides the default white screen while screen is still locked.
Same with i3lock-fancy-multimonitor and blur effect from imagemagick

**Comment by Airblader** [comment]
Can you please give some useful information such as the i3lock version etc.?

**Comment by eoli3n** [comment]
i3lock: version 2.7-100-gb07ec97 (2017-02-17)
on Archlinux, problem appears last week on my 2 laptops

**Comment by Airblader** [comment]
Are you using a compositor?

**Comment by eoli3n** [comment]
I am : compton

**Comment by Airblader** [comment]
Does the bug appear when you disable compton? If so, can you build i3lock from git and see if it is fixed there already by the latest commit? 

Also that compton version is pretty old (because compton hasn't released in forever). Building it from source is something I'd generally recommend.

**Comment by eoli3n** [comment]
Killing compton seems solve the bug.
I use the latest git version of compton ``Latest commit b7f43ee  on 7 Sep 2016``

... Bug seems not present anymore, without doing nothing... hm will try on my work laptop tomorrow, thx for your help and sorry for that poor bug report ;) I keep it open to let you know what solved the bug.

**Comment by Airblader** [comment]
I'm actually going to close it because the issue has disappeared and we don't support compositing with i3lock anyway. But if you do find anything out please do let us know. If it comes back, let's talk about it some more :-)

**Comment by eoli3n** [comment]
At work
- recompiling last compton from git
- restart compton
- compile i3lock from git
Problem persists

**Comment by Airblader** [comment]
If it works with that, you could try a git bisect on the main i3lock repository. But like I said, compositing is not supported in i3lock, so if disabling compton makes the issue disappear we do not consider it a bug (you could wrap `killall compton; i3lock; compton -b`).

If we do find the issue and it's an easy fix we will of course consider it.

**Comment by eoli3n** [comment]
I understand it :) no problem
