### ISSUE TITLE
i3lock seems to be drawn behind Chrome's fullscreen

### ISSUE THREAD

**Issue by IgnusG** [i3/i3lock#124]
If I run i3lock when in Chrome's fullscreen the lock seems to be rendered behind it. It still accepts input and Chrome doesn't but you can see what is happening on the screen.
This does not happen with any other window in fullscreen - only Chrome (Chromium). 

The debug log is exactly the same for both
```
[i3lock-debug] device = 3
[i3lock-debug] found Xinerama screen: 1366 x 768 at 0 x 0
[i3lock-debug] scaling_factor is 1, physical diameter is 190 px
[i3lock-debug] device = 3
[i3lock-debug] Watching window 0x01c00003
[i3lock-debug] redraw_screen(unlock_state = 0, pam_state = 0)
[i3lock-debug] scaling_factor is 1, physical diameter is 190 px
X11 Error received! sequence 0xd5, error_code = 4
~ > [i3lock-debug] process_xkb_event for device 3
```

I don't find it too annoying since I can just quit fullscreen and return on unlock.

**Comment by Airblader** [comment]
Are you using a compositor and if so, does not running it fix the problem?

**Comment by IgnusG** [comment]
I'm using compiz as a window manager with compositing turned on. I disabled the compositing plugin but the problem persists. The screen lock works under normal circumstances and other app's fullscreen views but with chrome in fullscreen renders underneath it.

**Comment by Airblader** [comment]
I cannot reproduce this, i3lock is correctly above the fullscreen. So I'm not sure where the issue would be – i3lock, compiz or Chrome.

**Comment by IgnusG** [comment]
I'll try messing with it a little. I so far suspect incorrect behavior caused by compiz (not many people use it as standalone WM so not many will be affected I suppose)
Closing for now

**Comment by IgnusG** [comment]
Issue was with compiz's unredirect fullscreen windows (to remove tearing) - solution is to either add i3lock into the matcher or turn off the feature. Works without problems either way. This setting is part of the composite plugin but for whatever reason disabling the plugin itself did not solve the issue
