### ISSUE TITLE
PAM as an optional dependency

### ISSUE THREAD

**Issue by fturco** [i3/i3lock#134]
I like i3lock but I don't think I need PAM on my system. Frankly I don't even know what PAM is exactly. Is there any chance PAM could become an optional dependency of i3lock instead of a mandatory one?

Please see [this](https://www.reddit.com/r/i3wm/comments/6armq8/i3lock_without_pam/) Reddit thread for other details.

**Comment by Airblader** [comment]
We avoid introducing conditional flags in the build configuration. If you feel really strongly, please patch it out locally. For OpenBSD it is excluded from the compilation as PAM is not available there, so it should be a fairly easy patch.
