### ISSUE TITLE
telegram notifications still appear while screen is locking by i3lock 

### ISSUE THREAD

**Issue by YanhaoMo** [i3/i3lock#138]
system: Debian sid
i3 version: 4.13-1
i3lock version 2.9.1-1
telegram-desktop version: 1.1.10-1

I have suffered this for a long time.

**Comment by Airblader** [comment]
Are you using a compositor?

**Comment by YanhaoMo** [comment]
yes, I'm using compton @Airblader

**Comment by YanhaoMo** [comment]
Is compton the reason to this?

**Comment by Airblader** [comment]
Yes. You you disable it (at least while the screen is locked), it should work. We don't support compositing.

**Comment by YanhaoMo** [comment]
OK, thanks for answering.

**Comment by YanhaoMo** [comment]
btw. Is i3-gaps support compositing?

**Comment by Airblader** [comment]
i3-gaps doesn't ship its own i3lock.

**Comment by YanhaoMo** [comment]
I see, thx
