### ISSUE TITLE
It is not clear how to: ".. specify either a background color or a PNG image ...."

### ISSUE THREAD

**Issue by rinmalavi** [i3/i3lock#143]

**Comment by Airblader** [comment]
What exactly is unclear when you look at the "options" section of the man page and how do you suggest to improve it?

**Comment by rinmalavi** [comment]
Pardon me. Become too reliant on internet and expected this information to be presented in Readme.md where this possibility is presented.
Completely  forgot to check man page, where it is clear enough.
Feel free to delete this.

**Comment by Airblader** [comment]
Thanks! The primary source should be the man page, we don't really intend the README to be a full overview of all the options given that most users will not actually come close to the repository anyway.
