### ISSUE TITLE
[Feature] if directory is given to -i flag, pick random image in dir

### ISSUE THREAD

**Issue by crypdick** [i3/i3lock#144]
I am trying to set up i3lock to use one of the wallpapers downloaded by [Variety](https://launchpad.net/variety). However, the `-i --image` flag only accepts the path of a specific image. It would be great if it would accept a directory, recursively searched for all images, and picked one at random.

**Comment by Airblader** [comment]
We're not looking to add this kind of functionality in i3lock as this can be trivially handled by a simple wrapper around i3lock in a language of your choice. Example:

    i3lock -i $(find /path/to/files -name "*.ext" | shuf -n1)

**Comment by crypdick** [comment]
Thanks @Airblader. That was not trivial for me. Now I need to figure out how to convert to PNGs in line...

**Comment by Airblader** [comment]
You can use `convert` from ImageMagick for that, for example.

**Comment by scookdev** [comment]
This works for me:

``` bindsym $mod+Shift+o exec i3lock --tiling -i $(ls /path/to/files/*.png | shuf | head -1)```
