### ISSUE TITLE
"Lock failed" when maintaining shortcut key

### ISSUE THREAD

**Issue by maekclena** [i3/i3lock#146]
System: 
Arch Linux 4.12.8
i3 4.13
i3lock 2.9.1

Steps to reproduce: 
1. Set i3lock on a combination of a modifier and another key, for example Shift+L;
2. Press both keys, launching i3lock;
3. Release the modifier key and maintain the other.

i3lock closes with the message "Lock failed".

Log:
```
[i3lock-debug] device = 3
[i3lock-debug] found Xinerama screen: 1366 x 768 at 0 x 0
[i3lock-debug] scaling_factor is 1, physical diameter is 190 px
[i3lock-debug] redraw_screen(unlock_state = 0, auth_state = 2)
[i3lock-debug] scaling_factor is 1, physical diameter is 190 px
[i3lock-debug] redraw_screen(unlock_state = 0, auth_state = 4)
[i3lock-debug] scaling_factor is 1, physical diameter is 190 px
```

**Comment by Airblader** [comment]
There is nothing we can do against this. If we cannot grab the keyboard because there is another grab active, then we aren't locking. That's just how X works.

**Comment by kopchik** [comment]
Is it possible to re-try failed operation?

**Comment by Airblader** [comment]
We have always retried it a thousand times. We also recently merged a change that applies another trick to try and get it to lock.
