### ISSUE TITLE
xkbcommon error

### ISSUE THREAD

**Issue by Kyle-Thompson** [i3/i3lock#147]
Running i3lock gives the following error message

    xkbcommon: ERROR: Couldn't read Compose file /usr/share/X11/locale/: No such device
    [i3lock] xkb_compose_table_new_from_locale failed

version: 2.9.1

**Comment by stapelberg** [comment]
Sorry for the late reply.

Can you clarify whether you’re using a keyboard layout which supports the compose key, and whether it produces the key symbols you expect, or whether this is merely a cosmetic issue?

**Comment by Kyle-Thompson** [comment]
From the time that I posted this the issue has been resolved. I've encountered a new one though that I'll make a new issue for.
