### ISSUE TITLE
screen change during sleep not detected

### ISSUE THREAD

**Issue by bebehei** [i3/i3lock#148]
When locking the screen, putting the box to sleep, and change the screen configuration during it, i3lock does not change its screen configuration upon wakeup.

In contradiction to i3lock, i3 adapts its windows after sleep to the change and shows on the newly added screen the desktop. Although the desktop is always empty and i3lock still has the keyboard and mouse focus, it would be better, if i3lock always requeries the screen configuration after sleep.

**Comment by Airblader** [comment]
Note that we do already resize when we receive `ConfigureNotify` events, which I guess in this case aren't sent. Perhaps we can also react to specific RandR events without actually using RandR, but just to use them as a trigger.

**Comment by stapelberg** [comment]
I’m optimistically closing this under the assumption that commit c311d1c5a3e555ebac575de45f635c326fce5822 fixed it. Please re-open if it still happens.
