### ISSUE TITLE
Feature Request: Yellow Circle

### ISSUE THREAD

**Issue by lasers** [i3/i3lock#15]
This feature will help differentiate between i3lock with black background, blank DPMS, monitor warming up, monitor standby, et cetera.... 

If I'm using xautolock to suspend the machine (or suspend it manually). I can't determine easily when I'm back on i3lock without pressing something to trigger the circle and unlock the password.

If I don't press anything for a while, the machine will quickly suspend again... I would not press anything because I'm either waiting for the monitors to warm up once the connection has been made and possibly because i3lock's background remains black.

I understand that this can be easily solved by using different background color but I wish to keep my background pure black for a sake of simplicity. I wish to have an option to make i3lock more consistent by always displaying the circle regardless of its feedback (or lack of one). Here's a mockup.

![i3lock](https://cloud.githubusercontent.com/assets/852504/7469338/0b6bab68-f2d8-11e4-93ca-f435a0f007ba.png)

**Comment by stapelberg** [comment]
I’m hesitant to adding new options. I think chosing a different background color than black would also solve your problem, and hence it’s just a matter of personal taste. Am I missing something?

**Comment by lasers** [comment]
It's difficult to do that. I like black. I don't want #222222 because I might like #151515 or #121212 later down the road. I like knowing that my i3lock is fully black (and not light/dark gray) because there is nothing to configure... Just black. It's one less color option to worry about. That's my personal taste.

This one isn't. I'm looking for a way to acknowledge that I'm looking at i3lock (with black background) to see whenever if the screen is suspended, simply locked, or still restoring. The best way could be to introduce something that will always be on the screen (Be it a yellow circle, a clock, or a padlock logo. An option to toggle on permanent yellow circle would be very consistent with i3lock's other circles... and possibly reduce the feelings of annoying wrong passwords (and/or) disappearing magic acts.

I'm using i3lock --dpms and the monitors aren't always speedy after suspend. Sometimes the connections will drop. When I pressed something to leave suspend state, the monitor leaves standby... (With a message -- Xorg 219 something), then the connection get dropped, monitor goes standby for a second or two, connection restored, then the screen will appear. Sometimes it'll return back to suspend state because I'm not typing anything... or it will... and I didn't acknowledge it yet. Pressing backspace will bring it back to suspend state too, I think... possibly on first few hits... as I wait for the monitors to be active.

I'm looking for a way to acknowledge that so I can start typing in the password and not second-guessing by hitting random keys to see if it's i3lock. Also, I like having my i3bar displayed all times. I want to do that with i3lock too. The idea of i3lock appearing when I'm typing things is akin to having hidden i3bar appearing when I'm holding/pressing $mod. It's sometimes annoying that i3lock will disappear. I prefer leaving that to DPMS.

**Comment by stapelberg** [comment]
Note that I don’t recommend to use the `--dpms` flag, see also http://cr.i3wm.org/patch/469/

I understand where you’re coming from with regards to the rest of your comment, but I still think that bottom line, it’s better to not introduce a new option and just use a different background color to solve your problem.

I’m marking this as closed, sorry — see also https://faq.i3wm.org/question/778/why-is-patch-not-merged-and-made-optional/
