### ISSUE TITLE
Merge with i3-color-lock

### ISSUE THREAD

**Issue by shibumi** [i3/i3lock#151]
Hello,
I would like to ask for the reason why the brilliant changes of i3-color-lock: https://github.com/chrjguill/i3lock-color are not getting into this repository.

The features of that project are a nice addition to the original i3lock and I would prefer to have these features in i3lock. 

Is there any reason why the features of i3lock-color are not in i3lock yet?

**Comment by Airblader** [comment]
Because we are not going for maximal eye candy or configurability. i3lock is a safety relevant application and thus we want to keep it simple. Also see https://faq.i3wm.org/question/778/why-is-patch-not-merged-and-made-optional/
