### ISSUE TITLE
notify-send / Signal popups appear on top of lock screen

### ISSUE THREAD

**Issue by YoloClin** [i3/i3lock#152]
notify-send and signal desktop application ( https://chrome.google.com/webstore/detail/signal-private-messenger/bikioccmkafdpakkkcpdbppfkghcmihk?hl=en ) and probably all other browser applications which support popups (slack, Facebook messenger ) appear on top of the i3lock screen. I would expect these to appear 'under' the screen.

To reproduce: `i3lock & sleep 2; notify-send "Hello world"; sleep 3; pkill i3lock`

**Comment by Airblader** [comment]
See #22, #96, #130 and finally #133

**Comment by YoloClin** [comment]
Great. I'll be sure to purge i3lock from my system. Thanks for your help!x
