### ISSUE TITLE
Block input during verify

### ISSUE THREAD

**Issue by begormania** [i3/i3lock#16]
Hi there!

I would suggest to not accept any input during the verifying process. Some days ago, I found myself unable to login because a funny coworker spamed the lockscreen with false inputs (hitting a single button and enter for a few hundred times..). Hence the login was unavailable until every input was tested (.. denial of service attack?).

**Comment by stapelberg** [comment]
This is already done with https://github.com/i3/i3lock/commit/8a630bec651be1670f45c022a35399529ab0e523. Since Debian is now unfrozen, I’ll do a new i3lock release soon (need to update libxkbcommon first) which will include that commit.
