### ISSUE TITLE
Image out of memory error

### ISSUE THREAD

**Issue by Kyle-Thompson** [i3/i3lock#161]
When called as `i3lock -i ~/path/to/image.jpg', I'm given an out of memory error instead of the image. The file is 127K and the path is valid.

**Comment by orestisf1993** [comment]
#68, #114

**Comment by Kyle-Thompson** [comment]
I saw the PNG issue but since my path was valid it didn't seem to apply. Didn't know about the jpg issue though. Thanks for posting.
