### ISSUE TITLE
Lock can be circumvented by opening rofi

### ISSUE THREAD

**Issue by saligrama** [i3/i3lock#162]
I use i3lock combined with glindste/xwobf to lock the screen, blurring the window contents behind it. This is paired with xss-lock to lock on suspend when my laptop lid is closed.

This part works fine, but when I open the laptop up there is a delay before i3lock can lock the screen. During this time I can open rofi, and this causes i3lock to fail. A video of the bug is here:

https://www.youtube.com/watch?v=bJyUOYb_6Rk

I'm using Arch Linux with i3-gaps on a Gigabyte Aero 14 with an i7-6700HQ and a GTX 1060 (proprietary drivers with bumblebee). i3lock is version 2.9.1-2. I'm not sure if this bug is reproducible on systems without a dedicated GPU.

**Comment by Airblader** [comment]
#35

This might perhaps be addressed in the (not yet released) #155. If not, you can try opening a ticket for rofi asking them to exit when they lose input focus.

**Comment by Airblader** [comment]
As of right now it is released, in version 2.10. Sometimes things happen fast.

**Comment by Airblader** [comment]
https://github.com/DaveDavenport/rofi/issues/728
