### ISSUE TITLE
Users can circumvent i3lock by typing ctrl-alt-(1-6) and using an active session

### ISSUE THREAD

**Issue by throwawayi3lock** [i3/i3lock#166]
X allows users to hit ctrl-alt-(1-6) and login to a terminal. If all of these sessions are logged out, this issue isn't a problem, but if a user has not done so, someone can check and see that an open shell is available.

A fix should disable access to these alternate ctrl-alt terminal sessions while locked. i3lock should not rely on users remembering to log out of those standard terminals any more than it should rely on them remembering to close their keepass session before locking.

Come to think of it I'm pretty sure a lot of locking mechanisms can be circumvented this way. DFV

**Comment by Airblader** [comment]
These keys are managed by the kernel. There's nothing we can do about that. I think there's an option in X to disable them, though.
