### ISSUE TITLE
escape animation removed in 2.10

### ISSUE THREAD

**Issue by kpcyrd** [i3/i3lock#169]
After updating i3lock I've noticed that pressing esc doesn't bring up the i3lock wheel anymore.

I used to press this button to bring up the i3lock wheel which disappeared after some seconds to verify the screen is indeed locked by i3lock (in a compulsive sorta way).

I'm not sure this counts as a [valid bug][0], but I would appreciate if this feature could be re-introduced. :)

[0]: https://xkcd.com/1172/

**Comment by Airblader** [comment]
#164
