### ISSUE TITLE
i3blocks (i3bar) shows when using bar mode hidden in i3

### ISSUE THREAD

**Issue by ghost** [i3/i3lock#173]
The bar is showing when locked and mod4 is pressed(which is set to display the bar). 
spesific config 
`bar {
        mode hide
        hidden_state hide
        modifier $mod
}` Where $mod is Mod4.
This is probably not a huge problem, but thought i'd mention it.
Regards

**Comment by eplanet** [comment]
Hi! Thanks for reporting the issue. However I cannot reproduce it using your configuration and latest `i3` (`4.14-181-g458e2a2e`) and `i3lock` (`2.10-3-g6b53758`) versions. When I lock my screen and press Mod4, the bar remains hidden.

**Comment by ivarsu** [comment]
That's odd, i do not know how to get the same detailed version str, but running `i3 --version` outputs `i3 version 4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors` and `i3lock --version` outputs `i3lock: version 2.10 (2017-11-25) © 2010 Michael Stapelberg`. Am running `manjaro 17.1.3 i3 community edition`, and using blurlock as a screenlocker but tried recreating using just plain i3lock and the problem persists.

**Comment by Fabian-G** [comment]
Can confirm, but the problem only persists if a compositor is running(in my case compton).
Without compton pressing mod while i3lock is active will sometimes result in a very short flickering at the bottom of the screen.
With compton active i3bar is shown full time while the mod key is pressed. Additionally, if the urgent hint for a workspace is set, the bar will also show full time.

* i3 version 4.16.1 (2019-01-27)
* i3lock: version 2.11.1
* compton version v5.1

**Comment by JohnAZoidberg** [comment]
I have the same issue, also just when running compton:
- i3 version 4.16.1 (2019-01-27)
- i3lock: version 2.10 (2017-11-25)
- compton: 0.1_beta2.5

**Comment by JohnAZoidberg** [comment]
I also had a floating window pop up, while it was locked. That was shown, too.

**Comment by stapelberg** [comment]
This issue is tracked in https://github.com/i3/i3lock/issues/204

**Comment by tkapias** [comment]
I use `jaq` to parse the json in the above solution but jq works with the same args.
