### ISSUE TITLE
Unnecessary pointer check

### ISSUE THREAD

**Issue by valkheim** [i3/i3lock#176]
Hi,

According to [xcb documentation](https://xcb.freedesktop.org/manual/group__XCB__Core__API.html#ga094470586356d1764e69c9a1882966c3), `xcb_connect()` always return a non-NULL pointer. The comparison to NULL on [line 810](https://github.com/i3/i3lock/blob/master/i3lock.c#L810) looks unnecessary.

This is how monsterwm-xcb implements it : https://github.com/Cloudef/monsterwm-xcb/blob/master/monsterwm.c#L1260

**Comment by SegFault42** [comment]
Hi, 

Code corrected, Pull Request submitted.

Thank you for your report.

**Comment by eplanet** [comment]
Just to be precise: will be corrected by pending PR #177. :-)
