### ISSUE TITLE
Save a command to launch after unlock

### ISSUE THREAD

**Issue by GuillaumeSeren** [i3/i3lock#18]
Hi there,
I am using i3lock with a systemd service to secure my unlock by using the fork option,
it work well, but I would like to send a command just after the end of i3lock.

I made a wrapper (here: https://github.com/GuillaumeSeren/i3lock-wrapper), it work's for simple lock,
but it *break* the the suspend if I use it, so I used my wrapper for lock / and just i3lock for suspend.

So my question is, do you know a better way to do it ?

In my opinion, it would be great to *store* a command and to launch it / fork it after the end of i3lock, do you think it can be done ?

Guillaume.

**Comment by Airblader** [comment]
I uses non-forking with a trap:

````
trap "…" EXIT
```

Seems to work fine for me. Why do you fork if you want to wait anyway?

**Comment by GuillaumeSeren** [comment]
Hey Airblader,
thank's for your quick reply.

I know I can watch the PID and launch my command after, it works I did it in my wrapper script,
but it break the suspend.

So maybe I miss something, but I think forking is needed to let the suspend work.

**Comment by stapelberg** [comment]
I think you should explain how you are running that script so that we get a bit more context.

**Comment by GuillaumeSeren** [comment]
Hello @stapelberg , yes this is how I do 

I created a systemd service, like explained in the debian / arch wiki here: https://wiki.debian.org/ScreenLockingOnSleep and here: https://bbs.archlinux.org/viewtopic.php?pid=1170536#p1170536
```
[Unit]
Description=i3lock
Before=sleep.target

[Service]
User=username
Type=forking
Environment=DISPLAY=:0
ExecStart=/usr/bin/i3lock -d -e -f -c 000000

[Install]
WantedBy=sleep.target
```
Then enable it, in systemd and you go, you have to unlock after come back from suspend, witch is want we want.

But I am searching a way to trigger on the 'unlock event' witch basically is end of the pid of i3lock to launch some command on unlock, here deactivate DPMS of my screen, but could be useful for many things.

So if I have done a script witch poll the pid of a running i3lock to check it, it work for locking only but it didn't work for locking + suspending (in my test at least), so I would like to embed the call to a script in i3lock.

Guillaume

**Comment by stapelberg** [comment]
@GuillaumeSeren I think what you should do (based on what you describe you want) is create a service file with `After=sleep.target`, see also https://bbs.archlinux.org/viewtopic.php?id=151640

There’s nothing we need to change in i3lock for your use case.

**Comment by GuillaumeSeren** [comment]
@stapelberg Yes I think too but I was just asking to know if you get a better solution.

Guillaume
