### ISSUE TITLE
Could not connect to X11 if using lxdm

### ISSUE THREAD

**Issue by nenad** [i3/i3lock#180]
Since I moved to using `lxdm` I noticed my systemctl service for locking on suspend started failing with the following message:

```
Mar 17 17:15:34 xps betterlockscreen[10043]: No protocol specified
Mar 17 17:15:34 xps betterlockscreen[10043]: i3lock: Could not connect to X11, maybe you need to set DISPLAY?
```

This is how the script looks like:
```
[Unit]
Description=Lock screen on suspend

[Service]
User=nenad
Environment=DISPLAY=:0
Type=forking
ExecStart=/usr/bin/betterlockscreen -l

[Install]
WantedBy=suspend.target
WantedBy=sleep.target
```
The `betterlockscreen` is a very simple image manipulator which uses i3lock (https://github.com/pavanjadhaw/betterlockscreen/)

LXDM puts the `.Xauthority` file in `/run/lxdm/$UID/.Xauthority`. I symlinked it from there to `~/.Xauthority` and it works now, but I'm not sure if this can be fixed in i3lock itself.

**Comment by stapelberg** [comment]
i3lock uses XCB, which uses libXau, which pretty much every piece of software uses for X authentication, so there shouldn’t be a difference here.

My guess is that lxdm sets the `XAUTHORITY` environment variable, resulting in programs picking up the correct location without needing the symlink. In your service file, try setting not only `DISPLAY`, but also `XAUTHORITY`.

**Comment by nenad** [comment]
Thanks for the answer! I can't test it since I've moved to using sway, but I'm pretty confident your solution will work.

**Comment by alexsoul99** [comment]
Thanks a lot, this helped me...
