### ISSUE TITLE
Lock fails when invoking dmenu after i3lock.

### ISSUE THREAD

**Issue by fristonio** [i3/i3lock#189]
Steps to reproduce:
* `sleep 5 && i3lock`
Try to invoke dmenu before i3lock executes.

i3lock will show **Locking** but the lock eventually fails.

**Comment by jannikw** [comment]
I am running i3lock version 2.10 (2017-11-25), which i assume contains the fixes for #35. The problem as described by @fristonio seems to persist... :(

**Comment by Airblader** [comment]
The merged "fix" is only an attempt to make it work. It won't work in all cases. Making it reliable simply isn't possible in X11, so just wait while it says "Locking..." before leaving your machine.

**Comment by jannikw** [comment]
Ah too bad. 

> so just wait while it says "Locking..." before leaving your machine.
This only sucks when trying to lock and suspend when the laptop's lid is closed. ;)

**Comment by Airblader** [comment]
Then just make sure to close dmenu and other »similar« windows (ie, context menus etc.) :-)

**Comment by jannikw** [comment]
I found workaround which I can live with: Combining i3lock and [physlock](https://github.com/muennich/physlock) by executing `i3lock || physlock -d` on suspend ensures that one of the two locks the device. That's better than doing `i3lock || shutdown now` to make sure the device is not left unlocked after resuming.
