### ISSUE TITLE
Can't unlock if first password entered is wrong

### ISSUE THREAD

**Issue by mindfuckup** [i3/i3lock#19]
When I enter the wrong password to unlock the screen, I have problems with the next try. I have to press backspace or esc to delete the wrong password, so I can enter the new one. If you don't know the workaround, you're not able to login.

I'm using the current Version from the Arch Linux Repository:

    $ i3lock --version
    i3lock: version 2.7 (2015-05-20) © 2010 Michael Stapelberg

**Comment by Airblader** [comment]
I can't reproduce this. Since i3lock uses PAM, you might have a timeout to wait for after your wrong attempt. Can you try using the wrong password, waiting a few seconds and then trying again?

**Comment by mindfuckup** [comment]
Ok, I did some tests:

Test 1: Lock screen, enter wrong password, enter correct password (screen doesn't unlock), hit ESC, enter correct password (screen does unlock):

    Jun 04 17:46:39 eris unix_chkpwd[14964]: password check failed for user (emanuel)
    Jun 04 17:46:39 eris i3lock[14953]: pam_unix(i3lock:auth): authentication failure; logname= uid=1000 euid=1000 tty= ruser= rhost=  user=emanuel

Test 2: Lock screen, enter wrong password, hit ESC, enter correct password (screen does unlock):

    Jun 04 17:48:31 eris unix_chkpwd[15335]: password check failed for user (emanuel)
    Jun 04 17:48:31 eris i3lock[15325]: pam_unix(i3lock:auth): authentication failure; logname= uid=1000 euid=1000 tty= ruser= rhost=  user=emanuel

Test 3: Lock screen, enter wrong password, wait about 5 seconds, enter correct password (screen does unlock):

    Jun 04 17:50:02 eris unix_chkpwd[15647]: password check failed for user (emanuel)
    Jun 04 17:50:02 eris i3lock[15625]: pam_unix(i3lock:auth): authentication failure; logname= uid=1000 euid=1000 tty= ruser= rhost=  user=emanuel

Interessting is the first Test: I had two failed unlocks (1x wrong and 2x right password) but in the logfile there's only one failed login attempt.

Then i got an idea:

I use a shortcut which calls `i3lock -u --dpms -c 333333 --pointer default`. So with the `-u` Flag, I don't see the indicator. I think this was my problem: When I misstyped, it was still "verifying" and "wrong" and my nex attempt was false, because the keys are not accepted when this info is shown. 

So it was a typical user error :(
Sorry for interrupting, I closed the issue. Thanks anyway :)

**Comment by Airblader** [comment]
Yeah that's what I mentioned above. Please note that this is PAM and not i3lock. And it's a security features to avoid password spamming (brute force).
