### ISSUE TITLE
Memory Leak After Unlocking

### ISSUE THREAD

**Issue by DragonBallZeke** [i3/i3lock#199]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

After unlocking, I am receiving the following message in terminal: 
<pre>=================================================================
==13625==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 33 byte(s) in 1 object(s) allocated from:
    #0 0x7fcd8c389b50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7fcd82c25578 in g_malloc (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x50578)

SUMMARY: AddressSanitizer: 33 byte(s) leaked in 1 allocation(s).</pre> 

## Reproduction Instructions

1.) Run `i3lock` 
2.) enter password
3.) recieve memory leak warning
4.) profit? 
## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.11-c-23-g5bbdd02 (2018-07-10, branch "master") © 2010 Michael Stapelberg
</pre>

**Comment by stapelberg** [comment]
Sorry for the late reply. We don’t use g_malloc in i3lock, so the leak must be somewhere else. Perhaps we indirectly cause it, or perhaps we’re just not to blame.

Further investigations and/or pull requests welcome :)

**Comment by stapelberg** [comment]
Closing as the reporter is inactive.
