### ISSUE TITLE
status on new release?

### ISSUE THREAD

**Issue by matthewrsj** [i3/i3lock#201]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[x] Other (Please describe in detail)
</pre>

## Current Behavior
Any status update on when a new release will be made? Particularly interested in the fix in #171 so it doesn't segfault on .jpg files.

## Expected Behavior
Latest release to not segfault on .jpg files

## Reproduction Instructions

```
i3lock -i '/path/to/file.jpg'
```

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 2.10
</pre>

**Comment by stapelberg** [comment]
I can release a new version. Note however that the change you’re referring to merely improves the error reporting, it won’t make i3lock actually load JPG files.

**Comment by matthewrsj** [comment]
yep, I understand that. Thanks!

**Comment by stapelberg** [comment]
New release out!
