### ISSUE TITLE
Missing documentation on compilation

### ISSUE THREAD

**Issue by t-wissmann** [i3/i3lock#206]
## I'm submitting a…
<pre>
[ ] Bug
[ ] Feature Request
[x] Other: Lack of documentation
</pre>

Can you please tell in your README.md or in a separate INSTALL file how one can compile i3lock? I tried for several minutes but did not succeed (and I'm not an expert on autotools).

**Comment by Airblader** [comment]
The instructions are essentially the same as with i3 itself, and typically looking at how packages are built in a distribution is a good way to find out as well. Here's the AUR version minus some adaptions:

```
autoreconf --force --install

rm -rf build/
mkdir -p build && cd build/

../configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --disable-sanitizers

make
make install
```

I'm happy to have a PR to add some INSTALL file, but (and that would ideally be included in there), generally speaking a user shouldn't have to build from source on their own, but instead install it through their package manager.

**Comment by eplanet** [comment]
I think it's a good idea to add these instructions, along with a command to install required libraries. But couldn't we just do that in the README itself, in the requirements section?

We could add a warning that the preferred way to use `i3lock` is with the distributed package but shouldn't discourage people from building it.

**Comment by Airblader** [comment]
We can certainly add a list of dependencies similar to i3, but I don't see how we can add a command for it. That just depends so greatly on the distro and version of distro both in what the command itself is as well as what the dependencies are named there.

**Comment by Airblader** [comment]
Merged the PR now, so closing this.

**Comment by t-wissmann** [comment]
Thanks a lot!
