### ISSUE TITLE
Feature Request: spec to resize unlock indicator 

### ISSUE THREAD

**Issue by gabrielfsousa** [i3/i3lock#212]
## I'm submitting a…

<pre>
[ ] Bug
[x ] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Expected Behavior

Spec to specify the size of the unlock indicator , ( for me is to big :) )

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 2.11.1
</pre>

**Comment by Airblader** [comment]
We're trying to keep the configuration surface of i3lock to a minimum. If "too big" refers only to personal taste preferences, I don't think we'd want to add such an option. If you don't like the indicator, you can already disable it entirely.

**Comment by eplanet** [comment]
I wouldn't be against that feature, especially because I'd like it bigger (just tried by fiddling [BUTTON_RADIUS](https://github.com/i3/i3lock/blob/master/unlock_indicator.c#L25) value). But we'd have to set a minimum because it can hide the displayed text if too small.

**Comment by gabrielfsousa** [comment]
thanks, i  have this error when compiling ... is a lib missiong ?
```
make[2]: Entering directory '/home/pti00225/Downloads/i3lock-2.11.1/x86_64-pc-linux-gnu'
  CC       i3lock-dpi.o
  CC       i3lock-i3lock.o
  CC       i3lock-randr.o
  CC       i3lock-unlock_indicator.o
  CC       i3lock-xcb.o
  CCLD     i3lock
/usr/bin/ld: i3lock-i3lock.o: in function `input_done':
i3lock.c:(.text+0x612): undefined reference to `pam_authenticate'
/usr/bin/ld: i3lock.c:(.text+0x644): undefined reference to `pam_setcred'
/usr/bin/ld: i3lock.c:(.text+0x658): undefined reference to `pam_end'
/usr/bin/ld: i3lock-i3lock.o: in function `main':
i3lock.c:(.text+0x195c): undefined reference to `pam_start'
/usr/bin/ld: i3lock.c:(.text+0x1979): undefined reference to `pam_strerror'
/usr/bin/ld: i3lock.c:(.text+0x19b1): undefined reference to `pam_set_item'
/usr/bin/ld: i3lock.c:(.text+0x19ce): undefined reference to `pam_strerror'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:526: i3lock] Error 1
make[2]: Leaving directory '/home/pti00225/Downloads/i3lock-2.11.1/x86_64-pc-linux-gnu'
make[1]: *** [Makefile:429: all] Error 2
make[1]: Leaving directory '/home/pti00225/Downloads/i3lock-2.11.1/x86_64-pc-linux-gnu'
make: *** [Makefile:411: all-all] Error 2
```

**Comment by eplanet** [comment]
The easiest you can do to install all dependencies is: `sudo apt build-dep i3lock`. Works on Debian/Ubuntu.

**Comment by gabrielfsousa** [comment]
i'm on fedora 29

**Comment by gabrielfsousa** [comment]
manage to compile, 
-clean all
-run configure again
-make -j8 

and is working :) thanks

**Comment by eplanet** [comment]
It should then work using `sudo dnf builddep i3lock`

**Comment by gabrielfsousa** [comment]
my changes
```
#define BUTTON_RADIUS 40
```
```
const double scaling_factor = get_dpi_value() / 150.0;
```
```
cairo_set_font_size(ctx, 16.0);
```
```
case STATE_AUTH_VERIFY:
                text = "…";
```

**Comment by stapelberg** [comment]
As @Airblader outlined, this falls under personal preference and hence won’t be changed. Thanks for understanding.
