### ISSUE TITLE
Indicate capslock/numlock before and/or while typing password

### ISSUE THREAD

**Issue by Markus00000** [i3/i3lock#225]
## I'm submitting a…

<pre>
[ ] Bug
[X] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Capslock and numlock status are shown only after an incorrect password has been entered. 

## Expected Behavior
Always show capslock and numlock status on the lock screen or as soon as the user is typing.

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 2.11.1
</pre>

**Comment by JanczarKurek** [comment]
Implemented, I'll make pull request after some code style fixes, probably tomorrow. :)

**Comment by stapelberg** [comment]
These improvements were released with i3 v2.14
