### ISSUE TITLE
OOM when piped valid PNG

### ISSUE THREAD

**Issue by owenthewizard** [i3/i3lock#227]
## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
```bash
import -window root /tmp/i3lock.png # take screenshot with ImageMagick
convert /tmp/i3lock.png -blur 10 - | i3lock -i /dev/stdin # blur with ImageMagick and pipe to i3lock
cat /tmp/i3lock.png | i3lock -i /dev/stdin # this also doesn't work
i3lock -i /dev/stdin < /tmp/i3lock.png # this does
```
Output:
```
Could not load image "/dev/stdin": out of memory
```
## Expected Behavior
`i3lock` should use the PNG as a background.

## Reproduction Instructions
See "Current Behavior" above.

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.11.1 © 2010 Michael Stapelberg
</pre>

**Comment by owenthewizard** [comment]
Any update on this?

**Comment by eplanet** [comment]
Hello! I wouldn't be surprised that `i3lock` doesn't support `/dev/stdin` fd. I suppose the workaround of storing `convert` result to a temporary file works?

```bash
convert /tmp/i3lock.png -blur 10 - > /tmp/i3lock_blurred.png
i3lock -i /tmp/i3lock_blurred.png
```

**Comment by owenthewizard** [comment]
It supports it when redirected, but not when piped. In my use case I want to avoid using a temporary file.

**Comment by owenthewizard** [comment]
Another working method:  
```
i3lock -i /dev/stdin < <(cat ~/Pictures/GIMP_Pepper.png)
```

Replace cat with any command, e.g. ImageMagick.

**Comment by owenthewizard** [comment]
Hmm, piping seems to work using raw images `--raw=WxH:fmt`.

**Comment by stapelberg** [comment]
Closing this as piping seems to work with raw images.
