### ISSUE TITLE
Man section for --inactivity-timeout is unclear

### ISSUE THREAD

**Issue by DrewMcArthur** [i3/i3lock#23]
The section of i3lock's man page regarding the -I --inactivity-timeout flag is unclear on the syntax.  Based on error messages, I've gathered that the flag requires an int to supply the time after which the screen disappears, however this was not evident at first in the man file. I'd suggest simply adding the underlined 'seconds' after the -I switch's syntax, to clarify that it's necessary.

**Comment by Airblader** [comment]
The description of the command begins with

> Specifies  the number of seconds […]

Is that really unclear?

**Comment by acrisci** [comment]
It's inconsistent with the rest of the docs. If the argument takes a parameter, it should indicate that in the manual.
