### ISSUE TITLE
Center round radius and position (eventually style)

### ISSUE THREAD

**Issue by Nox-404** [i3/i3lock#233]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Upon typing a password, it shows a centered circle with green arcs when typing a key

## Expected Behavior

The circle is positioned with an offset, with a smaller radius, different colors and texts

## Reproduction Instructions

> N/A

## Environment
<pre>
i3lock version: i3lock: version 2.10 (2017-11-25) © 2010 Michael Stapelberg
</pre>

Is it possible to add more customisation to the lock circle ?
Like position, texts, colors, size ?

**Comment by Airblader** [comment]
Thanks for filing this issue. We do not intend to make i3lock more customizable for visual purposes only as we want to keep the code footprint small. Thanks for understanding!
