### ISSUE TITLE
Indicate input on lock screen

### ISSUE THREAD

**Issue by Markus00000** [i3/i3lock#237]
## I'm submitting a…

<pre>
[ ] Bug
[X] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
The lock screen does not indicate whether there has already been input.

**Example:** I carry my laptop around and accidentally press a key on the lock screen. When I later try to unlock, I cannot see that there has been input. I type my password and it is incorrect due to an accidental key press some time ago. 

## Expected Behavior
Indicate in some way (text, icon, color, etc.) that input has been made. However, do not by default reveal input length.

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 2.11.1
</pre>

**Comment by orestisf1993** [comment]
You can clear the input with escape or ctrl-u

**Comment by Markus00000** [comment]
Thank you, I use escape whenever I know there is input. I would prefer to be able to see when I have to instead of prefacing my password with escape all the time.

**Comment by orestisf1993** [comment]
I think the unlock indicator should only show if there is input.

**Comment by Markus00000** [comment]
I think what you have said can be interpreted in two ways. Which one do you mean:

1. should only show if input is occurring in this very moment and then stop indicating
2. should only show if input has been made or not

**Comment by orestisf1993** [comment]
The unlock indicator only shows (at least for me and AFAICT from the code) when input has been made.

**Comment by Markus00000** [comment]
I understand what you mean now. I have never noticed this because my screen is turned off while the computer is locked. The first keystroke turns the screen on and reveals the indicator. As a consequence, I always see the indicator.

In this case, an indicator (which already exists as you said) can't help. Not the brightest line of thought...

Would a timeout option be possible after which all input is cleared? If there is no input for x seconds, forget all previous input.

**Comment by orestisf1993** [comment]
Yes a keypress "reveals" the indicator because you entered text. Press control or escape to enable your screen without entering text.

**Comment by Markus00000** [comment]
I might make a new feature request for a timeout option if the workarounds bother me too much.

Closing this issue now to avoid confusion. Thanks for your help!
