### ISSUE TITLE
Multi monitor: image only shown on one monitor

### ISSUE THREAD

**Issue by Ploppz** [i3/i3lock#242]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[x] Other - a change in an existing feature
</pre>

## Current Behavior
Running i3lock with the `-i` option, the specified image is only shown on the first monitor.

## Expected Behavior

Running i3lock with the `-i` option, the specified image is only shown on all monitors. Or alternatively, a way to specify an image for each monitor.

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: i3lock: version 2.12 © 2010 Michael Stapelberg
</pre>

**Comment by n1st** [comment]
Did you try with ```-t``` option ? Works well for me.

```
$man i3lock
-t, --tiling
              If an image is specified (via -i) it will display the image tiled all over the screen (if it is a multi-monitor setup, the image is visible on all screens).
```

**Comment by Ploppz** [comment]
Thanks, that a pretty good solution, except when the screens are of different resolution.
