### ISSUE TITLE
"i3lock -i xxx.png" error.

### ISSUE THREAD

**Issue by 178me** [i3/i3lock#251]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

i3lock -i ~/wallpaper/PNG.png
## Expected Behavior

show image
## Reproduction Instructions

Error information:
File "/home/yzl178me/wallpaper/PNG.png" does not start with a PNG header. i3lock currently only supports loading PNG files.
## Environment
Output of `i3lock --version`:
<pre>
i3lock version: i3lock: version 2.10 (2018-03-06, branch "tags/2.10") © 2010 Michael Stapelberg
</pre>

**Comment by Airblader** [comment]
Well, sounds like the image file is broken. Can you attach the image you are trying to use?

**Comment by 178me** [comment]
It should not be an image file issue. I tested it, and my friend had the same problem as me

**Comment by Airblader** [comment]
And thousands of people including myself use i3lock the same way without an issue, so therefore it cannot be an i3lock issue…? ;-)

Please attach the (or any) picture which does not work for you so we can actually rule out an issue with the image.

**Comment by 178me** [comment]
This is my attachment

**Comment by 178me** [comment]
Pictures I use
![Uploading PNG.png…]()

**Comment by 178me** [comment]
![PNG](https://user-images.githubusercontent.com/50314769/68385932-e0b5ff00-0195-11ea-93fb-7af253288b39.png)

**Comment by Airblader** [comment]
And that picture is missing the PNG file header, so the error is justified. Just run it through imagemagick with `convert foo.png foo_fixed.png` and you will see that now it works.

**Comment by 178me** [comment]
thanks
