### ISSUE TITLE
i3lock crash reports at i3lock.c:1299

### ISSUE THREAD

**Issue by D4N** [i3/i3lock#252]
Hi, I'm the package maintainer of i3lock in Fedora and have received an automated report that i3lock crashed a few times on user's machines. The full report can be viewed on [retrace](https://retrace.fedoraproject.org/faf/reports/2733069/) and points to an issue in: https://github.com/i3/i3lock/blob/abe1e3c85df10069e483ea14e4e6d87e9aed17fa/i3lock.c#L1299

Unfortunately, I have not observed this crash myself, so I cannot debug this further. Maybe you have an idea what is going on (appears to be related to PAM)?

**Comment by orestisfl** [comment]
Actual crash seems to be here: https://github.com/i3/i3lock/blob/2.12/i3lock.c#L292

**Comment by D4N** [comment]
Indeed, it appears to me that this is rather an issue in PAM.

**Comment by stapelberg** [comment]
Closing as the issue seems to be in PAM
