### ISSUE TITLE
Missing dependencies in Requirements section

### ISSUE THREAD

**Issue by tnptop** [i3/i3lock#253]
There seems to be some missing dependencies that are not listed in the Requirements section in README.md:
- `libxcb-image`
- `libxcb-xrm`

I was able successfully build after installing the two dependencies in addition to those listed in the readme. I'm not sure whether the missing dependencies are for the latest version (2.1.2) only, so there might be a need to check with the older ones.

## Environment
A freshly installed Ubuntu 18.04.

**Comment by Airblader** [comment]
Would you like to send a PR to add them? :-)

**Comment by tnptop** [comment]
Done in #255. Thank you :)

**Comment by Airblader** [comment]
Thank you! :-)
