### ISSUE TITLE
Fullscreen key passthrough

### ISSUE THREAD

**Issue by mendelmunkis** [i3/i3lock#258]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[ X] Other Vulnerability
</pre>

## Current Behavior

When certain programs are full-screen (Noted with Retroarch) keystrokes are sent both to i3lock and program.
## Expected Behavior

Only i3lock can see keys
## Reproduction Instructions

Start Retroarch in full-screen, load content. start i3lock, type in a password using a "p" somewhere while you type. retroarch content will have paused. (depending on what other keys are pressed there may be other affects as well) 
## Environment
Output of `i3lock --version`:
<pre>
i3lock version:  i3lock: version 2.11.1 © 2010 Michael Stapelberg
</pre>

**Comment by Airblader** [comment]
i3 grabs the pointer and keyboard (and exits if it fails to do so), so my assumption would be that retroarch uses raw keyboard events. I don't think there's a way for us to prevent that (and given that retroarch should not have focus this sounds like a bug there). A workaround on your side would be to use i3lock in combination with a wrapper script which switches to some other workspace (and then back) or similar.

**Comment by jer-gentoo** [comment]
Other screen lockers like XScreenSaver[0], xlockmore[1] and even slock[2] use `XGrabKeyboard`[3] and `XGrabPointer`[4] from libX11 to ensure no input leaks through.

i3lock instead uses `xcb_grab_pointer` fro libxcb but with `XCB_GRAB_MODE_ASYNC` for its 6th argument. Perhaps using `XCB_GRAB_MODE_SYNC` could fix this vulnerability? Notably the comment for that mode in xcb.c[4] simply says "keyboard mode" instead of something more descriptive of why that mode is being set.

[0] https://www.jwz.org/xscreensaver/
[1] https://www.sillycycle.com/xlockmore.html
[2] https://tools.suckless.org/slock/
[2] https://www.x.org/releases/X11R7.7/doc/libX11/libX11/libX11.html#XGrabKeyboard
[3] https://www.x.org/releases/X11R7.7/doc/libX11/libX11/libX11.html#XGrabPointer
[4] https://github.com/i3/i3lock/blob/master/xcb.c#L235

**Comment by Airblader** [comment]
The xcb docs is usually not extensive, but you can generally just look at the equivalent Xlib documentation. For example, the grab modes are explained here: https://tronche.com/gui/x/xlib/input/XGrabKeyboard.html

Indeed it might be worth trying this out. Could you just patch it locally and see if this resolves your issue?

**Comment by mendelmunkis** [comment]
setting the grab mode to SYNC has the unfortunate side affect of preventing any keyboard events from filtering through to i3lock as well.

**Comment by stapelberg** [comment]
I think for sync mode to work, you need to call `xcb_allow_events()`, too

**Comment by mendelmunkis** [comment]
Sorry I didn't have time to test until now. using xcb_allow_events() with grab mode SYNC still allows keys through to retroarch. I'm not sure if it's related but I noticed that xdotool is still reporting the whatever was running as having the focus while i3lock runs

**Comment by stapelberg** [comment]
Strange. i3lock grabs keyboard and mouse (and exits with an error message if it can’t), so nothing should go anywhere else.

What are the minimum steps to reproduce this issue?

**Comment by mendelmunkis** [comment]
I spent some time looking but can't find a simpler way to reproduce.

**Comment by stapelberg** [comment]
Can you link to a guide (or outline) the steps to get retroarch running to reproduce this please?

I haven’t used retroarch before and I want to make sure to follow the precise steps that trigger the issue for you.

**Comment by mendelmunkis** [comment]
1. Install (many distros have it in the repo and the provide a flatpack on flathub)
2. run the executable 
3. at the menu which the program starts at call i3lock (I used a i3 keyboard bind to test.)
4. press the right arrow key.
5. unlock
the menu will have shifted to the right

**Comment by stapelberg** [comment]
Thanks, I can reproduce this.

**Comment by stapelberg** [comment]
This is a retroarch issue. Followed up in their bug report: https://github.com/libretro/RetroArch/issues/7247

**Comment by mendelmunkis** [comment]
Thank you
