### ISSUE TITLE
Clear password shortcut

### ISSUE THREAD

**Issue by TannerYoung** [i3/i3lock#264]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Type a long password and make a mistake. Hold delete key for it to delete everything.

## Expected Behavior

Press "Ctrl-c" to clear the already typed password

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.12
</pre>

**Comment by Airblader** [comment]
You can already press Ctrl+u or Escape for that, see https://github.com/i3/i3lock/blob/master/i3lock.c#L458
