### ISSUE TITLE
--clock display skips seconds

### ISSUE THREAD

**Issue by jameh** [i3/i3lock#270]
## I'm submitting a…

<pre>
[X] Bug
[ ] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

`i3lock --clock` seconds don't update at regular intervals, and sometimes skip seconds.

## Expected Behavior

Seconds should update on screen at the correct intervals and not skip.

## Reproduction Instructions

Run 

```
i3lock --clock
```

and watch the seconds for half a minute, notice how they skip.

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.12.c.1 (2020-03-10, branch "tags/2.12.c.1") © 2010 Michael Stapelberg, © 2015 Cassandra Fox
</pre>

**Comment by orestisfl** [comment]
Hi, i3lock does not have such an option. You are looking for this fork: https://github.com/Raymo111/i3lock-color

**Comment by jameh** [comment]
oops, thanks. here's the bug over there: https://github.com/Raymo111/i3lock-color/issues/159
