### ISSUE TITLE
Feature request: Allow on screen keyboards like onboard with i3lock

### ISSUE THREAD

**Issue by arjunkc** [i3/i3lock#273]
## I'm submitting a…

<pre>
[ ] Bug
[X] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Currently, when I use i3lock to lock my 2-in-1 laptop, I have to move back to laptop mode to unlock my screen. So if there a way to have an on screen keyboard like 'onboard' work with i3lock, then that would be great.
## Expected Behavior

After fixing, invoking i3lock with
```
i3lock --keyboard /usr/bin/onboard
```
would make onboard appear on the screen

**Comment by stapelberg** [comment]
In general, i3 and i3lock aren’t meant to be used without a keyboard.

That said, I don’t know what’s required to implement this. If it’s simple enough, I wouldn’t mind.

**Comment by arjunkc** [comment]
The main virtual keyboards I can find are [here](http://florence.sourceforge.net/english/alternatives.html). You can run most of them on X, independent of DE. You simply click on the keyboard to enter keystrokes. They all work on lightdm or gdm login screens or any terminals. Is there any way for i3lock to call one of these programs and overlay them on the lockscreen? I think keystrokes would accepted just like a regular keyboard.

1. gok (gnome onscreen keyboard). Depends on gnome.
2. xvkbd. Doesnt seem to have too many dependencies, not dependent on gnome. Seems like an ideal candidate.
3. onboard. written in python, and ubuntu's default onscreen keyboard.
4. florence. Not dependent on gnome, but seems to have a few more dependencies than xvkbd.
4. cellwriter (this would be ideal for a tablet since it allows you to enter characters by writing with a stylus).

**Comment by stapelberg** [comment]
> Is there any way for i3lock to call one of these programs

Alternatively, can you start one of these immediately before starting i3lock?

**Comment by arjunkc** [comment]
If I do
```
onboard & 
i3lock
```
then i3lock screen covers the onscreen keyboard and I cannot see either the window or the mouse. For touchscreen input I would have to be able to see the on screen keyboard and the mouse.

**Comment by nvllsvm** [comment]
@arjunkc 

I worked around this by sleeping before starting onboard:
```
sleep 5 && onboard &
i3lock
```

**Comment by nvllsvm** [comment]
> ```
> onboard & 
> i3lock
> ```

This works for me.

**Comment by arjunkc** [comment]
I just tried this and it doesn't work for me: enable force window to top in onboard.

```
pkill -x onboard
onboard &
i3lock
```

I'm on i3lock 2.11.1 on debian buster running i3. Has there been a change in 2.12 that fixes this?

**Comment by nvllsvm** [comment]
Hm, I'm having trouble replicating it on my desktop. Might be working on my Surface Go due to it being so slow. Perhaps adding a sleep before onboard would fix it - not sure.

**Comment by arjunkc** [comment]
Ok, I guess it's working for me now. Steps:

1. Enable "force window on top" in onboard options.
2. /usr/bin/i3lock & onboard &

Works perfectly for me now. I can leave it open until you confirm it works for you. It even works with my suspend script.

```
pkill -x onboard
/usr/bin/i3lock
onboard &
systemctl suspend
```

**Comment by jackghg** [comment]
I comfirm. But even if it works its a unpredictable behavior, and probably should not work.

**Comment by Scorpion2185** [comment]
Is possible to achieve this on wayland? Now on Debian there is sxmo but only the sway version.<br>
`onboard` won't work there.

**Comment by Scorpion2185** [comment]
It doesn't work on sxmo-wm-dwm.
After I enabled "force window on top" in onboard options, I tried `/usr/bin/i3lock & onboard &` and the script:
```
pkill -x onboard
/usr/bin/i3lock
onboard &
```
Can I make it work?
Also a real implementation of a OSK for i3lock would be nice.

**Comment by arjunkc** [comment]
Is it possible to get it to play well with an osk like onboard?

**Comment by jackghg** [comment]
Try my keyboard: https://codeberg.org/jackc/OnKey

**Comment by Scorpion2185** [comment]
@arjunkc By doing as you said I can use onboard on my desktop, on openbox.
But not on mobile on sxmo-wm-dwm.

@jackghg I tried `i3lock & onkey &`, `i3lock & onkey -p &` and
```
pkill -x onkey
i3lock
onkey & #I tried both with and without -p 
```
Any suggestion?

**Comment by arjunkc** [comment]
@Scorpion2185 Doesn't work for me anymore for some reason, that's why I was asking. Maybe some OS update borked it. 

Quoting Scorpion2185 (2022-09-14 04:04:47)

**Comment by Scorpion2185** [comment]
@jackghg Maybe you can fork it and implement your keyboard or an option to use one.

**Comment by jackghg** [comment]
> @jackghg Maybe you can fork it and implement your keyboard or an option to use one.

Sorry i didnt see. try:
i3lock & sleep 3 && onkey -p
try it also for onboard
...try also my screen lock smlock :) also sflock isnt bad

**Comment by Scorpion2185** [comment]
@jackghg That didn't work for both onboard and onkey.

I cannot start smlock/sflock on my device, a PinePhone.

**Comment by jackghg** [comment]
@Scorpion2185 I made them for my pinephone :) 
sflock doesnt work probably becuse u r using wayland...

**Comment by Scorpion2185** [comment]
@jackghg No I am on x, as I said I am using sxmo-wm-dwm.
