### ISSUE TITLE
Indicator and time only shows on one monitor in vertical monitor layout

### ISSUE THREAD

**Issue by mihirlad55** [i3/i3lock#274]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When I set my dual monitors to be laid out horizontally using xrandr, the lock indicator and time show on all monitors. When I set my dual monitors to be laid out vertically using xrandr, the lock indicator and time only appear on my top monitor, but not on the bottom monitor.

## Expected Behavior
The indicator and time should appear at the same position on all monitors

## Reproduction Instructions
Use a dual monitor setup with both monitors having the same resolution. Use xrandr to set one monitor to output above the other. Execute the following script and pass the image path as an argument where the image shares the same resolution as both monitors:
```
#!/usr/bin/bash

IMAGE_PATH="$1"

insidecolor=#00000000
ringcolor=#ffffffff
keyhlcolor=#d23c3dff
bshlcolor=#d23c3dff
separatorcolor=#00000000
insidevercolor=#00000000
insidewrongcolor=#d23c3dff
ringvercolor=#ffffffff
ringwrongcolor=#ffffffff
verifcolor=#ffffffff
timecolor=#ffffffff
datecolor=#ffffffff
boxcolor=#00000066


i3lock -n \
    --timestr="%I:%M %p" \
    -t -i $IMAGE_PATH \
    --timepos='x+960:h-680' --time-align 0 \
    --time-font="Roboto" --timesize="80" \
    --datepos='x+960:h-645' --date-align 0 --datestr="%A, %B %d, %Y" \
    --date-font="Roboto" --datesize="24" \
    --clock \
    --insidecolor=$insidecolor --ringcolor=$ringcolor --line-uses-inside \
    --keyhlcolor=$keyhlcolor --bshlcolor=$bshlcolor --separatorcolor=$separatorcolor \
    --insidevercolor=$insidevercolor --insidewrongcolor=$insidewrongcolor \
    --ringvercolor=$ringvercolor --ringwrongcolor=$ringwrongcolor --indpos='x+960:h-575' \
    --radius=20 --ring-width=4 --veriftext='' --wrongtext='' \
    --verifcolor="$verifcolor" --timecolor="$timecolor" --datecolor="$datecolor" \
    --noinputtext='' --force-clock
```

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.12.c.1 (2020-03-10, branch "tags/2.12.c.1") © 2010 Michael Stapelberg, © 2015 Cassandra Fox
</pre>

Output of `xrandr --listactivemonitors`:
```
Monitors: 2
 0: +*DP-3-2 1920/544x1080/303+0+0  DP-3-2
 1: +eDP-1 1920/344x1080/194+0+1080  eDP-1
```

**Comment by stapelberg** [comment]
You’re reporting this in the wrong repository. i3lock doesn’t display the time or allow for a customizeable indicator.

Please report this in the appropriate version you’re using. Looks like it might be https://github.com/Raymo111/i3lock-color
