### ISSUE TITLE
Support configurable delay after wrong password?

### ISSUE THREAD

**Issue by nbeckman** [i3/i3lock#28]
When I type the wrong password in i3lock (frequently!) there is a considerable delay before I am allowed to retype my password.

I know that this is done for security reasons, but it would be nice if the delay were configurable so that I could shorten it. 

Even better would be exponential backoff so that the the first few times I mistype my password (normal) there is little delay, but after multiple repeated wrong passwords (uncommon) the delay is longer.

Thanks!

**Comment by stapelberg** [comment]
That feature comes from PAM, so you’ll need to look there for configuration/customization of the delay. i3lock just calls PAM :).
