### ISSUE TITLE
i3lock: error while loading shared libraries: libasan.so.5

### ISSUE THREAD

**Issue by anonymous133** [i3/i3lock#293]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[X] Other (Please describe in detail)
</pre>

## Current Behavior

When running i3lock in Terminal I get the following error message:

i3lock: error while loading shared libraries: libasan.so.5: cannot open shared object file: No such file or directory

## Expected Behavior
i3lock locks the screen

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 2.13-1
</pre>

gcc-libs-10.2.0-4 is installed.

I found nothing that could help me fix the issue. Maybe you know what I have to do?

Thank you for your help!

**Comment by stapelberg** [comment]
Where did you install i3lock from? You should install it from your Linux distribution.

If you built it from source and want to keep building from source, the easiest way to avoid this issue is to build with `--disable-sanitizers`

**Comment by anonymous133** [comment]
@stapelberg 
First I was using i3lock from the arch repository then I used i3lock-color from the AUR. That stopped working with this error. Then I tried to go back to i3lock from the Arch repo but the error persists :( And now I don't know how to fix it.

**Comment by stapelberg** [comment]
The expected output on Arch Linux is:

```
% i3lock --version
i3lock: version 2.13 © 2010 Michael Stapelberg
```

If you see something else (as you indicated in your first post), maybe you’re accidentally running a different version of i3lock than you expect?

If running /usr/bin/i3lock doesn’t work for you, even after completely removing and re-installing the package, please contact the Arch Linux support channels.

**Comment by anonymous133** [comment]
I couldn't run the version output because it produced the same error message. That's why I just typed the version number of the package I just installed from Arch Repo.

/usr/bin/i3lock did actually run!! Also the version output works with that! Thank you! Now I have to figure out why that is.. 

Thank you so much for your help!
