### ISSUE TITLE
Inactivity timeout only works for keyboard (not for mouse)

### ISSUE THREAD

**Issue by marcvs** [i3/i3lock#30]
I use /usr/bin/i3lock -d -I 5 -e -f
When hitting a key screen wakes up and sleeps again after 5s.

When moving the mouse it takes forever (more than 5s) until dpms makes screen sleep

When hitting a key after mouse was moved, dpms kicks in 5s later, like requested.

**Comment by marcvs** [comment]
Aktually, I personally think, mice should not wake up screens.

**Comment by stapelberg** [comment]
See http://cr.i3wm.org/patch/469/ for my thoughts on i3lock’s DPMS support. I’m considering actually making the i3lock DPMS feature a noop and forcing users to do it externally.

With that in mind, I don’t think there’s anything we should fix in i3lock itself, hence closing the ticket. Feel free to reopen if you disagree.
