### ISSUE TITLE
not locking all outputs / monitors

### ISSUE THREAD

**Issue by ThomasRausU** [i3/i3lock#302]
## I'm submitting a…

<pre>
[ ] Bug
[x ] Feature Request
[x ] Other (Please describe in detail)
</pre>

## Current Behavior
when locking via i3lock all outputs / monitors are locked. I want to just lock 2 of 3 outputs / monitors - is this possible? Any ideas? My use case is a third monitor just displaying stuff - this monitor should not be locked.

## Expected Behavior
It's configureable which monitors to lock

**Comment by Airblader** [comment]
This isn't possible with i3lock, and not really something we'd want to support either, sorry. Locking all but one monitor doesn't really make sense: locking is not just about blanking out the screen, it also means grabbing keyboard and pointer, which are independent of outputs.
