### ISSUE TITLE
I3lock-color broken betterlockscreen on Arch Linux

### ISSUE THREAD

**Issue by ynoalberto** [i3/i3lock#303]
## I'm submitting a…

<pre>
[ x] Bug
[ ] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 
<2.13.c.3-1>

**Comment by ynoalberto** [comment]
I3lock-color broken betterlockscreen causing this to not run

**Comment by kpcyrd** [comment]
hey!

This issue tracker is for i3lock, you're probably looking for one of those instead:

https://github.com/pavanjadhaw/betterlockscreen
https://github.com/Raymo111/i3lock-color

**Comment by ynoalberto** [comment]
Thanks you
