### ISSUE TITLE
Feature Request: Ability to run command on activity

### ISSUE THREAD

**Issue by pachacamac** [i3/i3lock#305]
## I'm submitting a…
<pre>
[ ] Bug
[x ] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Expected Behavior

Ability to run a command on events like `keyboard activity` and or `wrong password entered`.
This would allow running e.g. `fswebcam` or similar to take a photo/video of whoever tried to unlock your machine.

**Comment by stapelberg** [comment]
Thanks for your feature request.

Spawning processes while your screen is locked is too much of a footgun in terms of security.

I don’t want to add such a feature. Thanks for understanding.
