### ISSUE TITLE
'sudo i3lock' doesnt let unlock

### ISSUE THREAD

**Issue by theCollectiv** [i3/i3lock#307]
## I'm submitting a…

<pre>
[x ] Bug
[ ] Feature Request
[x] Other (Please describe in detail)
</pre>

## Current Behavior
`sudo i3lock` does not let you unlock the screen ...only switch off by hardware and restart possible
but `i3lock` works fine

## Expected Behavior
I was expecting that `sudo i3lock` behaves like `i3lock` ...an let u unlock the screen

## Environment
Output of `i3lock --version`:
<pre>
i3lock --version
i3lock: version 2.13 © 2010 Michael Stapelberg
</pre>
Using Ubuntu 20.04

**Comment by stapelberg** [comment]
This is most likely a PAM issue, not an i3lock issue.

I don’t know how to make this work, and we generally recommend running i3lock as unprivileged user only.

**Comment by theCollectiv** [comment]
Thx for reply. So I guess there is no work around available (I don't know anything about PAM)
Normally I wouldn't run into this issue ...but I had a script with sudo empowered  (with i3lock and pm-suspend [needs sudo] in it). So I guess I got to break the script in two scripts to deal with it.

**Comment by orestisfl** [comment]
Works fine for me. Remember that sudo password (this is typically **your** password) != root user password

> Note that by default Ubuntu has an invalid password field set for root, effectively making it impossible to login as root.

https://askubuntu.com/a/681739
