### ISSUE TITLE
enable multiple lockscreen images

### ISSUE THREAD

**Issue by Kaligule** [i3/i3lock#31]
i3lock could have an individual lockscreen image for every screen.
This could be achieved by using the -i flag multiple times or once with multiple paths.

**Comment by stapelberg** [comment]
The image-manipulating support of i3lock is intentionally kept very small. For this use-case, just concat the images using a third-party tool, e.g. GIMP.

**Comment by Kaligule** [comment]
Could you explain how this is about image manipulation?

**Comment by stapelberg** [comment]
I don’t want to argue about such details. The feature you’re asking for is easily achievable using third-party tools, which is the point that matters.

**Comment by Kaligule** [comment]
Of course you don't have to argue about it. I just hoped for an explanation or hint where to read more about it, since I really didn't think this has anything to do with image manipulation.

Thanks though, I will try to find one of the third party tools you mentioned.

**Comment by neruthes** [comment]
Script for dynamically choosing the current resolution before each i3lock execution:

```sh
SCREEN_RESOLUTION="$(xdpyinfo | grep dimensions | cut -d' ' -f7)"
BGCOLOR="0,0,0"
convert "/path/to/image.png" -gravity Center -background $BGCOLOR -extent "$SCREEN_RESOLUTION" RGB:- | i3lock --raw "$SCREEN_RESOLUTION":rgb -c 00ff33 -i /dev/stdin
```
