### ISSUE TITLE
systemd service for i3lock

### ISSUE THREAD

**Issue by snprajwal** [i3/i3lock#310]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Other (Please describe in detail)
</pre>

i3lock is generally utilised by most users when they are suspending/hibernating their device. This is not always done manually and is sometimes done by power managers. It would be beneficial to have a systemd service that can be enabled to fire i3lock upon suspend/hibernate

I am willing to submit a PR for this, do let me know if it will be accepted

**Comment by orestisfl** [comment]
I think these are usually provided by distro maintainers since their contents might differ per distro.

**Comment by snprajwal** [comment]
Afaik, systemd is distro-independent, and since the i3lock binary doesn't change names across distros, it should be fine

**Comment by Airblader** [comment]
Personally I would be in favor of providing _something_ here, because I also think the use case is common enough to warrant it, and it doesn't really add much of a maintenance cost.

However, I would let package maintainers take care of installing it into the correct place.

**Comment by stapelberg** [comment]
Ideally systemd units work across distributions, but it’s not always the case. But, in that situation, distribution maintainers can carry a distribution-specific patch, and there’s still value in us providing a standard unit that at least serves as a good starting point :)

I think this change would be best to discuss over an actual pull request to add the unit file.
Are there examples for what people typically put into the i3lock systemd unit?

Thanks

**Comment by snprajwal** [comment]
@stapelberg It will look something like this

/usr/lib/system/i3lock.service
```
[Unit]
Description=Run i3lock
Before=sleep.target

[Service]
User=%I
Type=simple
ExecStart=/usr/bin/i3lock
ExecStartPost=/usr/bin/sleep 1

[Install]
WantedBy=sleep.target
```

**Comment by stapelberg** [comment]
Thanks for the example!

Are we sure that this should be a system-wide service unit (in `/usr/lib/systemd/system`), as opposed to a systemd user session service unit (in `/usr/lib/systemd/user`)?

Also, why is the `ExecStartPost=/usr/bin/sleep 1` needed? That looks like a workaround for some other issue…?

**Comment by snprajwal** [comment]
@stapelberg 
>Are we sure that this should be a system-wide service unit (in /usr/lib/systemd/system), as opposed to a systemd user session service unit (in /usr/lib/systemd/user)?

This needs to be a system-wide unit as there are no systemd targets on the user level for any action apart from `shutdown`. A potential alternative would be to provide a bash script at `/usr/lib/systemd/system-sleep` instead. Systemd calls all executable scripts in this folder when `suspend.target` is invoked.

>Also, why is the ExecStartPost=/usr/bin/sleep 1 needed? That looks like a workaround for some other issue…?

As screen lockers may return before the screen is "locked", the screen may flash on resuming from suspend. Adding a small delay via ExecStartPost=/usr/bin/sleep 1 helps prevent this.

**Comment by stapelberg** [comment]
> This needs to be a system-wide unit as there are no systemd targets on the user level for any action apart from `shutdown`

Okay, thanks. So the User=%i means that people need to opt into using this unit file by running `systemctl enable --now i3lock@michael.service`, for example?



> As screen lockers may return before the screen is "locked", the screen may flash on resuming from suspend. Adding a small delay via ExecStartPost=/usr/bin/sleep 1 helps prevent this.

i3lock returns when it receives the first `MapNotify` event from X11, which means that i3lock’s window is now visible.

Can you remove the `sleep 1` please? Or are you saying that i3lock currently exits too early? If so, we should fix the code and not add `sleep` calls.

**Comment by snprajwal** [comment]
>So the User=%i means that people need to opt into using this unit file by running systemctl enable --now i3lock@michael.service, for example?

No, that indicates the user under whom the process should be run. The @ syntax is used only to enable services in specific contexts and is declared in the name, ex. the `getty@.service` file is used for `systemctl enable getty@tty1.service`

>i3lock returns when it receives the first MapNotify event from X11

In that case, we can safely remove the ExecStartPost :smile:

**Comment by stapelberg** [comment]
> No, that indicates the user under whom the process should be run. The @ syntax is used only to enable services in specific contexts and is declared in the name, ex. the `getty@.service` file is used for `systemctl enable getty@tty1.service`

I understand that, but what I’m trying to say is that if we ship `i3lock@.service`, then users will need to manually run `systemctl enable --now i3lock@michael.service` or similar, because the distribution package manager (e.g. `dpkg` on Debian) cannot know which user is the main user of the system — there might be multiple users configured on the same machine.

Is that something we can find a solution for? I would have hoped that we could use a systemd user session service unit, but you mentioned that won’t work because there’s no way to integrate with the `suspend` target.

In fact, looking at the `systemd-suspend.service` documentation, I see:

> Note that scripts or binaries dropped in /usr/lib/systemd/system-sleep/ are intended for local use only and should be considered hacks. If applications want to react to system suspend/hibernation and resume, they should rather use the [Inhibitor interface](https://www.freedesktop.org/wiki/Software/systemd/inhibit).

To use i3lock with the inhibitor interface, you can use `xss-lock --transfer-sleep-lock i3lock`.

Maybe we should just recommend using `xss-lock` instead of bothering with a systemd unit in this case?

**Comment by snprajwal** [comment]
>because the distribution package manager (e.g. dpkg on Debian) cannot know which user is the main user of the system

@stapelberg I think it makes sense to enable it for the user who is running the install command, since that's normally going to be the user who will be running the WM too. If a user who did not install i3lock themselves is going to use it, they can manually enable the unit, that would make sense since they're *choosing* to use it.

**Comment by stapelberg** [comment]
> @stapelberg I think it makes sense to enable it for the user who is running the install command, since that's normally going to be the user who will be running the WM too

I agree with this in principle, but I don’t think it’s possible (or permitted by policy) in Debian to make commands run as the user who started the package manager. The package manager always runs as root (often via `sudo`), and has no idea who invoked it.

**Comment by stapelberg** [comment]
Another issue seems to be that systemd does not reliably start i3lock before suspend, see also https://github.com/i3/i3lock/issues/311

I think we should recommend `xss-lock` as the preferred way to run i3lock, and no other way.
