### ISSUE TITLE
Feature request for unlocking without pressing enter key

### ISSUE THREAD

**Issue by abinlatheef** [i3/i3lock#313]
### I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Other (Please describe in detail)
</pre>

### Current Behavior

Need to press Enter key (Return Key) after entering password to unlock.

### Expected Behavior

Unlock as soon as password is typed. Like PIN on windows and android.

It would be good if we have a config for that. Please look into it.

**Comment by Airblader** [comment]
This isn't possible as far as I know, because we don't know how long the password is, and spamming every input to pam would just trigger auth failures and then potentially configured policies like back off.

It also seems like a very minor feature that doesn't offer a notable improvement.

**Comment by abinlatheef** [comment]
Ooh okay. Thanks for the clarification.
