### ISSUE TITLE
How to edit 3 wrong password attempt lock-out?

### ISSUE THREAD

**Issue by HarshalRathore** [i3/i3lock#314]
## I'm submitting a Question.

[ ] Bug
[ ] Feature Request
[x] Question

## Current Behavior

Users have 3 attempts or chances to unlock the i3lock if the user successfully manages to waste those 3 attempts i3lock times out for around 8-10 minutes so the user has to wait for the time out to end and again try to unlock the i3lock.

## Expected Behavior

I can't find a tag or parameter that I can provide to i3lock so it won't timeout after some dumb user(ME) manages to waste those 3 attempts. I have tried finding it in man pages, over the internet but couldn't find anything useful. Is this even possible in the first place? If not then this ISSUE of mine turns into a feature request.

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.13 © 2010 Michael Stapelberg
</pre>

**Comment by Airblader** [comment]
i3lock just uses pam, so you need to look into your system's pam configuration.
