### ISSUE TITLE
Warn user of caps lock before they enter their password

### ISSUE THREAD

**Issue by 18fadly-anthony** [i3/i3lock#316]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

If user has caps lock on, they will only be notified after entering their password incorrectly

## Expected Behavior

Put a "caps lock" warning as soon as user starts typing with caps lock on, not a huge issue but it would it would improve user experience

## Reproduction Instructions

1. lock screen
2. turn on caps lock
3. enter password

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: i3lock: version 2.13 © 2010 Michael Stapelberg
</pre>

**Comment by stapelberg** [comment]
There’s already a pull request for it: https://github.com/i3/i3lock/pull/236

I’m not sure where it stands, though.

**Comment by stapelberg** [comment]
fixed with commit https://github.com/i3/i3lock/commit/deaf8b9f0f8193b92bdf7f7631f82471296812d1
