### ISSUE TITLE
[bug] zoomed PNGs that have higher res than the monitor 

### ISSUE THREAD

**Issue by pc00per** [i3/i3lock#328]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

PNGs with bigger resolution than the display (4k image on 1080p monitor) doesn't fit. They have zoomed preset bydefault & only some portion is applied.

## Expected Behavior

i3lock should just fit the image (cropped if aspect ratio isn't right)

## Reproduction Instructions

Take this [4k background](https://wallpaperaccess.com/full/212885.png) as an example for i3lock (on a 1080p monitor)
`i3lock -i 212885.png`
## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.14.1 © 2010 Michael Stapelberg
</pre>

**Comment by stapelberg** [comment]
There are advantages to resizing the image outside of i3lock:

* i3lock can start up much faster (the difference is noticeable!)
* Your screen resolution rarely changes, but you lock your screen much more frequently than that. Instead of having i3lock resize the image over and over, resizing it outside of i3lock means the computation only needs to be done once.

**Comment by pc00per** [comment]
I've read man page which says
**`convert wallpaper.jpg RGB:- | i3lock --raw 3840x2160:rgb --image /dev/stdin`**
how to bind this exactly ?
Tried 
**`bindsym $alt+Control+Delete exec --no-startup-id $(convert wallpaper12442.png RGB:- | i3lock --nofork -i --raw 1920x1080:rgb --image /dev/stdin)`**
But no wallpaper showed up. What command goes where ?

**Comment by stapelberg** [comment]
Try without `$()`:

> **`bindsym $Mod+Control+Delete exec --no-startup-id convert wallpaper12442.png RGB:- | i3lock --nofork --raw 1920x1080:rgb --image /dev/stdin`**

Or possibly add quotes:

> **`bindsym $Mod+Control+Delete exec --no-startup-id "convert wallpaper12442.png RGB:- | i3lock --nofork --raw 1920x1080:rgb --image /dev/stdin"`**

Or move the i3lock call into a shell script and start that instead.

**Comment by pc00per** [comment]
Yeh that's right. Tried, but the output looks broken with pink & green lines. Means, the command worked perfectly, but converted RAW image isn't. Any idea ?

**Comment by pc00per** [comment]
The same issue again. The issue was resolution. Applied the image's resolution **`--raw 3999x2424:rgb`** then the colors are fine. But still, zoomed in. The manpage command doesn't scale the image. It just converts it into RAW image so that i3lock can process it. So pretty much useless. Need to find some other alternative.

**Comment by pc00per** [comment]
Okay. I've understood the thing. Even improvised it btw.
**`bindsym $alt+Control+Delete exec --no-startup-id convert $(ls ~/Pictures/background/** | sort -R | tail -1) -resize 1920x1920 $XDG_RUNTIME_DIR/i3lock.png | i3lock -i $XDG_RUNTIME_DIR/i3lock.png`**

- **`$(ls ~/Pictures/background/** | sort -R | tail -1)`** to utilize all of my wallpaper gallery
- **`-resize 1920x1920`** choosing biggest side of my monitor as the resolution limit (_doesn't affect aspect ratio & output will be filled_)
- **`$XDG_RUNTIME_DIR/i3lock.png`** outputs a PNG inside userside tmpfs to avoid disk writes

Thanks @stapelberg for suggesting to convert outside i3lock.
