### ISSUE TITLE
Feature request: Custom keyboard shortcuts

### ISSUE THREAD

**Issue by p9malino26** [i3/i3lock#329]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Other (Please describe in detail)
</pre>

It would be useful if the user were able to define keyboard shortcuts, map the shortcuts to commands, and be able to use the shortcuts when the screen is locked with i3lock. This would be useful for me in particular because I like to leave my laptop on playing music but don't want my kids to be able to access it. This would enable me to turn the screen off or play or pause the music or control the volume, all via keyboard shortcuts, without having to go through the pain of unlocking and then locking the laptop. 

Thank you for your time.

**Comment by orestisfl** [comment]
We like to keep the configuration options of i3lock to a bare minimum. This feature has been denied before in https://github.com/i3/i3lock/issues/52. [i3lock-color](https://github.com/Raymo111/i3lock-color) seems to implement this if you are looking for an alternative.
