### ISSUE TITLE
We need mp4 support

### ISSUE THREAD

**Issue by ulfgebhardt** [i3/i3lock#331]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

There seems to be no `mp4` support even tho we live in the 21. Century.

## Expected Behavior

mp4 support should be a thing.

## Reproduction Instructions

Try using mp4 file as lockscreen background material and be disappointed.

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.14.1 © 2010 Michael Stapelberg 
</pre>

## Additional context

I think this is a bit out of scope of what this tool should do and this issue is not 100% serious, but man, its Linux, everything is possible.

Just imagine how jelly the common Windows DAU on your workplace will look at your OS playing awesome lockscreen animations while his box is even struggling to boot in an adequate time. The Mac-"Power"-User will claim that the 5 Apple-Preapproved lockscreen animations he can purchase for 99$/month are super cool and sufficient tho.

**Comment by Airblader** [comment]
This isn't something we're looking to do.
