### ISSUE TITLE
i3lock doesn't accept correct password after entering incorrect ones.

### ISSUE THREAD

**Issue by renovat10** [i3/i3lock#335]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

i3lock will not unlock screen even after entering correct password if you've entered incorrect password before.
## Expected Behavior

i3lock should accept the correct password and unlock the screen after entering correct password.
## Reproduction Instructions

OS : EndeavourOS, Kernel : 6.0.12-arch1-1 shell : bash 5.1.16 Terminal Emulator : Alacritty
## Environment
Output of `i3lock --version`:
<pre>
i3lock version: version 2.14.1 (c) 2010 Michael Stapelberg
</pre>

**Comment by stapelberg** [comment]
I cannot reproduce this issue.

I’m guessing it’s a problem with your machine’s PAM configuration, not with i3lock itself.

**Comment by renovat10** [comment]
Weird that I couldn't reproduce it either. But I have ran into this issue at least twice and had to force poweroff my laptop. Will try to report the exact conditions if it happens again. What kind of additional info would you need in that case?

**Comment by stapelberg** [comment]
If it only happens occasionally, my first guess would be that maybe Caps Lock or Num Lock are enabled in that situation, though i3lock should display active modifiers.

The output of `i3lock --debug` (beware: contains your password in clear text!) would be useful, and your system’s PAM output (see journalctl probably).

**Comment by renovat10** [comment]
Okay
