### ISSUE TITLE
Non-standard License (not sure which SPDX identifier to use)

### ISSUE THREAD

**Issue by pennbauman** [i3/i3lock#337]
## I'm submitting a…
<pre>
[ ] Bug
[ ] Feature Request
[x] Other (Please describe in detail)
</pre>

The current license file appears to be a variation of the BSD 3-Clause license, by I can't identify exactly which one. I would like to use an accurate SPDX identifier while packaging i3lock, but I'm unsure how to do that currently.

Is the provided license a specific standard license? If so shouldn't the license file use standard license text so it can be easily identified?

**Comment by stapelberg** [comment]
It’s the 3-clause BSD license. 

I updated the text so that GitHub and other tools figure it out.

For licensing questions, it’s always worth checking out what Debian does: https://metadata.ftp-master.debian.org/changelogs//main/i/i3lock/i3lock_2.14.1-1_copyright

**Comment by pennbauman** [comment]
Thanks! I'll remember that, I was looking a Fedora's packaging which had it listed as MIT for some reason.

**Comment by stapelberg** [comment]
The MIT license is very similar, but 3-clause BSD has one extra clause. See https://fossa.com/blog/open-source-software-licenses-101-bsd-3-clause-license/ for details.
