### ISSUE TITLE
Please add functional for show layers (en,ru and etc)

### ISSUE THREAD

**Issue by oditynet** [i3/i3lock#338]
<pre>
[ ] Bug
[X] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
I want see a layers of keyboard then write a password (en , ru , etc.) and indicated about press CAPSLOCK

**Comment by stapelberg** [comment]
duplicate of https://github.com/i3/i3lock/issues/287

**Comment by oditynet** [comment]
Dear stapelberg. Please, show my commit about duble.
https://github.com/i3/i3lock/issues/287#issuecomment-1489976496
