### ISSUE TITLE
Option to compile i3lock without PAM on Linux

### ISSUE THREAD

**Issue by 2011** [i3/i3lock#339]
## I'm submitting a…

<pre>
[x] Feature Request
</pre>

Since you already offer (on OpenBSD) i3lock without using PAM, I wonder if you might offer a compile-time option to not use PAM on Linux (instead just using system authentication), which I hope would require only a modest amount of coding.

Glancing over the issues, it appears that PAM causes lots of problems (which it has for many years - I have used Linux for more than 25 years, and have kept PAM off of my systems during that entire period, which has saved me a great deal of grief).

**Comment by stapelberg** [comment]
No, we want to stick to PAM.

For a screen locker, it’s important to keep the number of code paths small.

See also https://michael.stapelberg.ch/posts/2019-05-23-optional-dependencies/

I’m using Linux for almost 20 years, and PAM never caused me grief :)
