### ISSUE TITLE
Better Computer Wake Handling.

### ISSUE THREAD

**Issue by Joseph-Melberg** [i3/i3lock#344]
## I'm submitting a…

<pre>
[ ] Bug
[X] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Pressing space to wake the computer results in the entered password being " {your regular password}"
## Expected Behavior
Wake the computer, enter the password, "{your regular password}"

## Environment
Output of `i3lock --version`:
<pre>
i3lock version:  all of them
</pre>

Anyways I submitted a pull request to add this feature.

**Comment by stapelberg** [comment]
Thanks for your pull request, but this doesn’t seem like a feature that’s broadly useful for enough people to justify the maintenance overhead.

I suggest you maintain this as a custom patch, or just wake your computer using a modifier key. E.g., press Shift to wake instead of Space.
