### ISSUE TITLE
Feature Request: Keyboard Language In Password/Lock Screen

### ISSUE THREAD

**Issue by ayjayt** [i3/i3lock#346]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Lock screen only shows capslock/numlock

## Desired Behavior

Lock screen might also show keyboard mapping- french, english, spanish, etc

## Impact

<pre>
[ ] This feature requires new configuration and/or commands
</pre>

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version:  4.22
</pre>

<pre>
- Linux Distribution & Version: Ubuntu Server (23, I think)
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by orestisfl** [comment]
Already done at https://github.com/i3/i3lock/pull/341
