### ISSUE TITLE
i3bar is shown in i3lock lock screen when it is positioned at the bottom with picom running

### ISSUE THREAD

**Issue by denppa** [i3/i3lock#347]
## I'm submitting a…

<pre>
[x ] Bug
[ ] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

`i3`'s default bar `i3bar` is shown on top of the `i3lock` lock screen when it is positioned at the bottom with `picom` running.

## Expected Behavior

The `i3lock` lock screen / color should hide everything on the desktop.

## Reproduction Instructions

Buggy config:
```
bar {
        status_command i3status
        position bottom
}
```
Replace `bottom` with `top` and it is hidden in the lock screen.

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.14.1 © 2010 Michael Stapelberg
</pre>
Debian Bookworm, i3wm v 4.22

**Comment by stapelberg** [comment]
Typically, i3lock raises its lock screen window above any other X11 window that obscures the lock screen (such as i3bar).

However, i3lock cannot raise its windows above a compositor.

The only known solution is to stop the compositor before running i3lock, then restarting the compositor afterwards: https://github.com/i3/i3lock/issues/333#issuecomment-1329881590

**Comment by denppa** [comment]
Thanks @stapelberg . I thought of this as well, though I feel like this constant restarting will drain the battery a lot quicker on laptops.

**Comment by stapelberg** [comment]
> though I feel like this constant restarting will drain the battery a lot quicker on laptops.

I doubt it will be noticeable. Starting a compositor is not a heavy operation.
