### ISSUE TITLE
password unrecognized

### ISSUE THREAD

**Issue by dev2projects** [i3/i3lock#348]
## I'm submitting a…

<pre>
[]
[ ] Feature Request
[* ] Other (Please describe in detail)
</pre>

## Current Behavior

I type in my password, hit enter and can't get past it. I'm using arch, having sddm installed and enabled. On my Ubuntu i3lock does work like a charm (same machine, same keyboard layout set - delatin-1) . I reboot my system, so I can get into it. 

## Expected Behavior

Type password, hit enter, and enter system.

## Reproduction Instructions

Arch linux, sddm enabled ? 

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: i3lock: version 2.13 © 2010 Michael Stapelberg

</pre>

**Comment by kpcyrd** [comment]
I'm guessing this is the [10 minute lockout after 3 failed attempts](https://wiki.archlinux.org/title/Security#Lock_out_user_after_three_failed_login_attempts) in the `pambase` package. You can disable this by editing `/etc/security/faillock.conf` and setting `deny = 0`, it's unrelated to i3lock.

**Comment by dev2projects** [comment]
Ok, changed the config file, and it makes no difference. It does not seem to be a bug of i3lock - I installed xlock from xlockmore, and it seems that it also does not care about me correctly typing in my password.

**Comment by stapelberg** [comment]
Might be issue #119? Either way, not an i3lock problem, but a PAM/configuration problem.
