### ISSUE TITLE
Custom password

### ISSUE THREAD

**Issue by YodaEmbedding** [i3/i3lock#350]
## I'm submitting a…
<pre>
[ ] Bug
[x] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Uses user's password.

## Expected Behavior
Option to specify a custom password or pin, e.g. `CUSTOM_PASSWORD=1337 i3lock`.

(In fact, a pin touchpad UI would be neat for touchpad users, but that's a separate feature request.)

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.13.c.5 (2023-07-28) © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2021 Raymond Li
</pre>

**Comment by stapelberg** [comment]
i3lock does not manage passwords. i3lock uses PAM for authentication. 

If you want to unlock with a different password, you need to configure the PAM i3lock config file accordingly.
