### ISSUE TITLE
numlock indicator is unaesthetic and not useful - can't disable?

### ISSUE THREAD

**Issue by Ten0** [i3/i3lock#352]
As of i3lock 2.15, as I type I always get a numlock indicator displayed. (I use black background)
This is not useful: no typo is ever due to people having accidentally enabled numlock and typing on their numpad. (Unlike Capslock indicator which would be very useful if there wasn't always XxxLock written at that place, which makes Capslock indicator easily go unnoticed)
It is unaesthetic: just the circle is much more stylish.

I'm not sure how to disable it.
The source code seems to show no option:
https://github.com/i3/i3lock/blob/d8e853e9865b7e340063144f70c72d804fc772f3/unlock_indicator.c#L158

Thanks,

**Comment by stapelberg** [comment]
> This is not useful: no typo is ever due to people having accidentally enabled numlock and typing on their numpad.

You’re correct when only thinking of full-size keyboards, but what motivated the numlock indicator is that a number of laptop keyboards have a numpad laid over their regular keyboard (see https://www.reddit.com/r/thinkpad/comments/j6wt74/numeric_keypad_functions_on_models_that_do_not/ for an example). 

When accidentally enabling numlock, certain parts of your password might not be possible to enter anymore, and it’s very irritating for users to get into that state without any visual hint as to what’s happening (laptop keyboards typically don’t have LED indicators in their numlock keys).

> It is unaesthetic: just the circle is much more stylish.
> I'm not sure how to disable it.
> The source code seems to show no option:

There is no option, and I don’t think I want to add one:

i3lock’s philosophy is to not make every visible element configurable to keep the configuration surface (and test matrix, and complexity) at a minimum. For example, all the colors in the unlock indicator are intentionally not configurable either. Different projects like https://github.com/Raymo111/i3lock-color have a different philosophy and offer more customization.

If you feel strongly about sticking to i3lock and getting rid of the numlock indicator, you could turn off numlock before starting i3lock and re-enable it afterwards (with a wrapper script as described in https://manpages.debian.org/testing/i3lock/i3lock.1.en.html#DPMS, for example).

**Comment by Ten0** [comment]
Thanks for the detailed answer 👍🙂
