### ISSUE TITLE
i3lock is pausing for 30 seconds after verifying my password

### ISSUE THREAD

**Issue by stratosgear** [i3/i3lock#356]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[x ] Other (Please describe in detail)
</pre>

## Current Behavior
There is a 30 sec delay after my password is verified before i3lock releases control back to me.  Being constantly exactly 30 secs is extremely suspicious, but I cannot find out why.

## Expected Behavior
I would expect after I finish typing my password for i3lock to immediatelish unlock the screen

## Reproduction Instructions

I tried to capture a strace to understand where the spend time went, but I cannot read the output.

I started it as: `strace -t -o i3lock.strace i3lock -n --debug `

I believe the relevant section is this:

```
00:07:15 recvmsg(6, {msg_namelen=0}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
00:07:15 poll([{fd=6, events=POLLIN}, {fd=7, events=POLLIN}], 2, 29994) = 0 (Timeout)
00:07:45 sendmsg(6, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\1\0\1\0\0\0\0\n\0\0\0\217\0\0\0\1\1o\0 \0\0\0/net/rea"..., iov_len=160}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 160
00:07:45 recvmsg(6, {msg_namelen=0}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
00:07:45 ppoll([{fd=6, events=POLLIN}], 1, {tv_sec=24, tv_nsec=999942000}, NULL, 8) = 1 ([{fd=6, revents=POLLIN}], left {tv_sec=24, tv_nsec=998965151})
```

where the 30 seconds delay in the strace output appears.

The i3lock debug did not show anything important.

Both outputs, are listed in their entirety in the following [gist](https://gist.github.com/stratosgear/f0a1644f138bfee36b4b32005ec3a6a4)

## Environment
Output of `i3lock --version`:
<pre>
➜  i3lock --version
i3lock: version 2.15-non-git © 2010 Michael Stapelberg

~ 
</pre>

I am running on nixos unstable, on a Framework 13" AMD laptop.

The exact same system configuration (nixos flake) is also running on my desktop and this problem does NOT appear there. 

Any ideas what  other system settings I should check, or to how further debug this?

Thanks!!!

**EDITED**: To add that in those 30 secs "Verifying..." is being displayed on the screen!

**Comment by stapelberg** [comment]
i3lock just calls PAM. You likely need to debug this on the PAM level. Does the system journal contain any messages when you use i3lock? Does the same problem happen with other screen lockers?

**Comment by stratosgear** [comment]
Well, it seems to be an fprintd issue, I am afraid. I was never able to debug the pam logs, but insistent googling found similar issues like mine.

I have turned off fprintd in i3lock with:

```
    security.pam.services.i3lock = {
      # i3lock doesn't support fprintd.
      fprintAuth = false;
    };
```
(I'm on nixos, btw)

This makes the issue go away, and after correctly entering the password the screen unlocks immediately.

It's a shame that there is this incompatibility, and I've seen other pending issues with i3lock and fprintd.  Looking forward for a potential fix.  

Closing for now!
