### ISSUE TITLE
Show PAM messages

### ISSUE THREAD

**Issue by Manouchehri** [i3/i3lock#38]
Displaying PAM messages somewhere might be useful, it'd be nice reminder for 2FA PAM systems.

```
~ > sudo whoami
YubiKey for `david': 
root
```

**Comment by stapelberg** [comment]
In general I agree, but it might be a bit tricky to find a good visual representation of these messages, as they typically don’t fit into our unlock indicator.

I suppose displaying them in a vertically and horizontally centered popup might be a good solution?

**Comment by Manouchehri** [comment]
How about inside the middle of the indicator?

**Comment by Airblader** [comment]
The indicator can be turned off, plus it's quite restricted space, so I think a kind of popup (with a size that adapts reasonably) is the better choice. We might also want the corresponding option to not show these messages?

**Comment by Manouchehri** [comment]
I would be happy with either.

The reason why I suggested inside the indicator circle is because the login
attempt counter text is already there, so I thought it might be easier to
reuse that.

**Comment by stapelberg** [comment]
You’re correct, but the text that we can show in the unlock indicator is only a couple of letters due to space constraints. This would cut off PAM messages very early, which might not be enough for the message to be useful for the user.

**Comment by Manouchehri** [comment]
Only around ~20 chars is needed for PAM messages I've come across, would enlarging the unlock indicator work?

**Comment by stapelberg** [comment]
No, I’d like to retain the current look&feel of the unlock indicator. Also, just because the PAM messages you found are ≤ 20 characters doesn’t mean all PAM messages are that short. Consider custom PAM modules etc.

I think we should try the popup overlay solution first.

**Comment by eplanet** [comment]
Are you guys talking about displaying messages you can get with the following function after unsuccessful call to `pam_authenticate`?
```cpp
const char *pam_strerror(pam_handle_t *pamh, int errnum);
```

**Comment by stapelberg** [comment]
No, PAM also allows for messages to be displayed before any authentication attempt takes place.

**Comment by kamushadenes** [comment]
+1 on that, I got stuck on fingerprint check once because I just totally forgot I was debugging it.

Took me a few tries to remember that and get to a (invisible) password prompt.

Could have just Ctrl+Alt+F(N) and killed i3, but it's a nice feature to have, and I don't consider it eyecandy at all.

**Comment by stapelberg** [comment]
I’m closing this issue in favor of tracking all PAM improvement work (which will help with fingerprint readers and other setups) in issue https://github.com/i3/i3lock/issues/217
