### ISSUE TITLE
i3lock don't handle compose and dead-keys

### ISSUE THREAD

**Issue by danielotero** [i3/i3lock#4]
Because of this reason, i3lock can't handle passwords with accents (e.g. á, ë) or other complex glyphs which are composed with 2 or more key presses.

This make the application pretty unusable for that kind of passwords.

**Comment by stapelberg** [comment]
Support for compose and dead keys was only introduced in libxkbcommon 0.5.0, see https://github.com/xkbcommon/libxkbcommon/commit/b05a05edbd4f386de8cb82003ed3408786478e0f

Implementing this means raising the dependency on libxkbcommon > 0.5.0, but that should be okay.

Pull requests very welcome, I most likely won’t work on this myself anytime soon.
