### ISSUE TITLE
Unable to unlock while 'wrong' is displayed

### ISSUE THREAD

**Issue by Nycrea** [i3/i3lock#45]
After I enter a wrong password, while displaying the 'wrong' message, I cannot submit a password by pressing the return key. I have to wait for the 'wrong' message to time out before pressing the return key to submit my password. 

What I am used to is that when I enter a wrong password, I can 'queue up' the right password immediately after and as soon as 'verifying' is done for the first (wrong) password it will start verifying the second (right) password and unlock. Whereas now I have to wait for the wrong message and only afterwards press the return key to unlock my pc.  

Arch Linux 4.2.5-1
i3lock: version 2.7 (2015-05-20)

**Comment by stapelberg** [comment]
This is intentional, to prevent “enter key spamming”, i.e. other people holding down the enter key while you’re not at your keyboard, preventing you from logging in when you return.
