### ISSUE TITLE
Keyboard layout hassle after upgrading 2.4 -> 2.6

### ISSUE THREAD

**Issue by romanrm** [i3/i3lock#56]
Hello,

Just today I upgraded to i3lock 2.6, and right away I notice a huge hassle, which made me switch away from xscreensaver a long time ago; and now it's here too.

Some background: I have two keyboard layouts on my computer: the regular Latin, and Cyrillic. My password is all Latin letters + digits.

Back on i3lock 2.4 it did not matter which keyboard layout I had selected on my desktop before going into the lock mode. Whatever I typed on the lock screen, was accepted by i3lock as Latin characters. I enter my password, the screen unlocks, all is well.

Enter 2.6. Now apparently the keyboard layout from the desktop is remembered also while in the i3lock mode. So after coming back to my computer, I enter my password, it says "bzzzt wrong!", I enter once more, wrong again, I figure I can't be mistyping so repeatedly and then realize -- dammit, what I type now goes to i3lock as Cyrillic! I press the layout switch keys, then retype my password once more, and finally it's typed in the Latin layout and accepted.

So I am checking change logs, and of course for "2013-06-09 i3lock 2.5" it says: "• NEW DEPENDENCY: Use libxkbcommon for input handling. This makes input handling much better for many edge cases." You probably think it's an amazing feature which made life for many people easier -- except for us, the actual users of multiple keyboard layouts. Such misfeatures which actually end up being the users' worst nightmare, it just makes me want to cry. Why one after another (first xscreensaver, now i3lock) you all step into the same pitfall.

Now one solution for this whole thing would be to add the current keyboard layout indicator to the lock screen. Which is how e.g. Windows does it. But I would argue it's not the best one. I believe barely anyone uses non-Latin (Cyrillic) passwords here, due to possible issues with inability to enter Cyrillic on certain consoles, or wrong layouts, encodings problem, etc. Also I like that i3lock is as simple as possible (possibly contributing to security), not having any extra widgets on the lock screen etc.

My suggestion would be to return i3lock to the original mode of operation (i.e. Latin only input), and adding an option to change this behaviour if the user wants.

As for me I guess I can downgrade to 2.4, it seems to still work on Debian Jessie. And of course after downgrade the problem is immediately and 100% solved. But I hope you will tell me there is hope and I won't have to keep using this old version forever from now on.

**Comment by Airblader** [comment]
> My suggestion would be to return i3lock to the original mode of operation (i.e. Latin only input), and adding an option to change this behaviour if the user wants.

I don't think this is a good idea. I think the commit was an improvement and in general a user will expect their typical keyboard layout to be used.

**Comment by romanrm** [comment]
@Airblader as it is currently, we don't know at the i3lock screen which layout is being used.

"Typical" is not an answer for someone who uses two or three languages and layouts on their computer to communicate in about equal portions.

The only way to find out is to enter your (possibly long and complex) password, ensuring you didn't mistype, and then see it not accepted. Only that's how you figure out you are on the "wrong layout".

The worst part is that i3lock **remembers** whatever has chosen at the time the screen was locked, and I **do not** -- having been away from my computer for hours/days and then returning later and trying to unlock.

**Comment by Airblader** [comment]
I definitely understand your problem, but for many other users, using some layout they might not be using usually is not a solution either.

I currently like displaying the layout most, but let's see what @stapelberg thinks.

**Comment by stapelberg** [comment]
I recommend you use a wrapper script around i3lock which ensures your current layout is latin.

Closing as this isn’t a bug, but rather an instance of https://xkcd.com/1172/ :).

**Comment by romanrm** [comment]
> I recommend you use a wrapper script around i3lock which ensures your current layout is latin.

Sure that's one option, but to preserve the previous behavior it'll have to be a rather sophisticated script which would first remember the current layout (can you even save it with setxkbmap?), switch to Latin before launching i3lock, then restore it to what it was on the desktop so that I can continue typing in whatever language it was at the time.

Or I could simply stay on the older version, which is easier at this point (until it stops installing in new distros) and also solves the issue.

> Closing as this isn’t a bug, but rather an instance of https://xkcd.com/1172/ :).

Sorry but no similarities and I don't know how can you laugh at this problem and hint that it's one user's weird setup issue. It's not. This will affect 100% of users who have more than one keyboard layout on their computer. And that's **NOT** a weird and uncommon situation if you consider the world at large outside of the few Latin-alphabet-only countries, it **IS** the norm. I described the problematic workflow introduced step by step and in IMO excruciating detail, can you maybe re-read it and try imagining it? Every password entry now randomly becomes 2 to 3 attempts for everyone. That's not just me, that's not my weird setup. The only solution to avoid is to pick a numeric-only password. And 100% of people in those countries will hit that, do you recommend that every user writes a script?

Admittedly I might be the only one to report the problem, but it might be because I'm one of the few of those users who have multiple layouts configured **and** want to use i3lock, the "normal people" just use whatever locker comes with GNOME or KDE these days. Heck, the normal people just use Windows. So the funny-XKCD-haha part in my case is not the layout thing, **it's the whole "trying to use i3lock" thing**, sorry.

Perhaps you simply don't care about anyone needing anything other aside English (hey, nobody cared in the 70s, that's why "7-bit encodings" are a thing). Guess nothing we can do about that, after all you're probably not getting paid for this, certainly I'm not the one paying you to order to work on one problem or another, so why fix it if it's not something that affects you personally.

Still rather disappointing to see.

**Comment by stapelberg** [comment]
> remember the current layout (can you even save it with setxkbmap?), switch to Latin before launching i3lock, then restore it to what it was on the desktop so that I can continue typing in whatever language it was at the time.

In https://github.com/i3/i3lock/issues/56#issue-128514967 you were writing that whenever you return to your computer, you don’t want to remember which layout you’re using. By always setting your layout to latin, you can always assume it to be latin.

Regardless, if you want to remember the layout, `setxkbmap -print` will display the current layout.

The rest of your post makes me angry, so I’ll not engage in a discussion.

**Comment by Airblader** [comment]
> This will affect 100% of users who have more than one keyboard layout on their computer.

Switching to properly using the set layout is in fact a major usecase for those who use different layouts. I don't agree that this will be an issue for 100% of those people because I assume that a lot of people remember what layout they were using.

How do you instantly start typing after unlocking, knowing which layout you are in, but don't know that two seconds earlier? Is the first thing you do really to look at your indicator everytime? Even if it is, I don't think that's how it is for everyone (or even most people).

Using the layout the user set means using the layout *the user wants to use when typing on their computer from this point forward*. It really makes more sense this way.

> the "normal people" just use whatever locker comes with GNOME or KDE these days

Most i3 users probably don't even run anything like GNOME or KDE.

> Perhaps you simply don't care about anyone needing anything other aside English

That's a pretty strong accusation and I think this is not fair. We, most of all Michael, in fact try very hard to provide the best support for keyboard layouts and languages. Michael himself worked hard on improving this a lot in i3 4.11, in fact. And AFAIK, Michael himself uses Dvorak or some other "non-normal" layout.

Again, this change was made explicitly to *properly support* keyboard layouts. You're complaining here about i3lock respecting the setting you chose in your system rather than ignoring it. It's sort of beyond me how you twist this into Michael not caring.

**Comment by romanrm** [comment]
> whenever you return to your computer, you don’t want to remember which layout you’re using. By always setting your layout to latin, you can always assume it to be latin.

It's not that I don't want to, I just don't. And that's only talking about the i3lock screen, but once I'm back to my desktop I most likely remember what's the current layout (see below).

> How do you instantly start typing after unlocking, knowing which layout you are in, but don't know that two seconds earlier?

Because if I see XChat with a Russian IRC channel in front of me, I remember I was using Russian to chat to them;

or a Japanese board for discussing anime, I'll probably remember that the UIM/Anthy Japanese IME is active when I start typing.

or this Github comment window where I'm typing halfway through this post, then of course I'm expecting it to continue typing in English.

Heck, on my desktop there's probably a tray indicator somewhere, showing what the current layout is (even though I just rely on the above hints and don't use one).

But the i3lock screen gives no such hints whatsoever, it's always the same.

> Most i3 users probably don't even run anything like GNOME or KDE.

I meant computer users in general. To be honest personally I have only a vague idea of what "i3" is, I just use i3lock with Xfce4.

> We, most of all Michael, in fact try very hard to provide the best support for keyboard layouts and languages.

And this is exactly why this is so so so shocking to me. You coded this XKB support thinking it makes things better -- but it doesn't, it makes them much worse for exactly your target audience you coded this for -- and I'm at a loss regarding how to make you realize that.

**Comment by Airblader** [comment]
> You coded this XKB support thinking it makes things better -- but it doesn't

I beg to differ and I think we are not going to come to an agreement here.

Given the tone that you used before, I am going to do something I haven't had to do yet and lock this thread. As Michael said, use a wrapper script to force your lock screen to disregard what you told your system to do. But this is no place for the sense of entitlement, demands or accusations you used before.

i3lock is aimed to be a lightweight and simple lockscreen. You may find that you're happier with the full blown kind of lock screen provided by DEs.
