### ISSUE TITLE
i3lock with sudo never logs in (Ubuntu 14.04 with i3)

### ISSUE THREAD

**Issue by JZL** [i3/i3lock#58]
I am running i3 on Ubuntu 14.04. If `i3lock` is run with `sudo`, it always says the password is incorrect (if it is run without it, it runs perfectly). As per #43 , I compiled and installed from the git source but it still did not work. Is there anything I can do?

**Comment by stapelberg** [comment]
Does your `root` user actually have a password? I.e., what is the output of `su -c whoami`?

**Comment by JZL** [comment]
It asks for a password then `su: Authentication failure` (I typed my password correctly). As per http://askubuntu.com/questions/446570/why-does-su-fail-with-authentication-error , I think the problem is Ubuntu does not have a root account, just allows an interactive sudo shell

**Comment by stapelberg** [comment]
Yep, AFAICT, your root account doesn’t have a password. Once you set one, i3lock will be able to authenticate.
