### ISSUE TITLE
Numpad not working correctly

### ISSUE THREAD

**Issue by DerEnderKeks** [i3/i3lock#65]
If I try to enter a number on my numpad while numlock is enabled nothing happens. Only if i deactivate numlock it detects the number correctly but any other application does not.

**Comment by stapelberg** [comment]
Which version of i3lock are you using?

**Comment by DerEnderKeks** [comment]
Version 2.5

**Comment by Airblader** [comment]
That's almost 3 years old. Please update to the latest version and see if you can reproduce the issue.

**Comment by DerEnderKeks** [comment]
In version 2.7 it works. Thanks!
