### ISSUE TITLE
JPEG support

### ISSUE THREAD

**Issue by boughtonp** [i3/i3lock#68]
I want to use jpg files on my lock screen.

Is JPEG support deliberately excluded, or simply not included because it doesn't come with Cairo?

It looks like there's [cairo_jpg](https://github.com/rahra/cairo_jpg) which would provide the necessary functionality.

Is that something that could be added to i3lock? (Or is there a fork which supports JPEGs?)

**Comment by Airblader** [comment]
Is there a specific reason not to use something like imagemagick to just convert it to png?

**Comment by boughtonp** [comment]
That means duplicating a file every time the image is changed.

**Comment by stapelberg** [comment]
jpeg is excluded because it doesn’t come with cairo. I’m not keen on adding a new dependency just to support jpeg.

**Comment by lindhe** [comment]
I get that the target audience for i3lock might not be your average Joe, but jpeg is (based on statistics I made up, but seems reasonable) more common than png. Especially for photos. So it's a rather common case to have a jpg laying around that you want to use as a background.

Sure you *can* convert it, but is it reasonable to ask that from the user? Maybe. Would it be more convenient for the user if the program supported jpg naively? Definitely.

Also, it does not give a nice error message when loading with a jpg. For me it just says `Could not load image "Pictures/images/wallpaper.jpg": out of memory`. Should probably say "Can only load PNG images.".

**Comment by stapelberg** [comment]
See #114 for details about the error message; I agree that should be improved.

I also hear what you’re saying, but the answer remains that the arguments don’t outweigh the cost of an additional dependency.

**Comment by lucianoq** [comment]
@Airblader Actually I found some specific reasons.

```
$ time -p scrot -t 10 qq.png
real 0.53
user 0.48
sys 0.01

$ time -p scrot -t 10 qq.jpg
real 0.11
user 0.06
sys 0.02

$ time -p convert qq-thumb.jpg -resize 1000% qq.png
real 1.68
user 2.05
sys 0.11

$ time -p convert qq-thumb.jpg -resize 1000% qq.jpg
real 0.18
user 0.57
sys 0.11

$ time -p convert qq-thumb.png -resize 1000% qq.png
real 1.53
user 1.93
sys 0.15

$ time -p convert qq-thumb.png -resize 1000% qq.jpg
real 0.24
user 0.65
sys 0.18
```
Or, aggregated:
```
$ time -p sh -c "scrot -t 10 qq.jpg && convert qq-thumb.jpg -resize 1000 qq.jpg"
real 0.14
user 0.14
sys 0.03

$ time -p sh -c "scrot -t 10 qq.png && convert qq-thumb.png -resize 1000 qq.png"
real 0.66
user 0.65
sys 0.03
```
That means that I could have an image in 0.14 instead of 0.66 (4x improvement)

**Comment by crypdick** [comment]
I don't understand. How big can jpeg dependencies possibly be? How hard would it be to make a fork that supports jpeg? Not supporting the most common image format strikes me as ridiculous.

**Comment by Cynary** [comment]
JPEG would be extremely useful. I'm trying to make it so my lock screen is a blurred screenshot at the time of locking. It is pretty annoying to do as the processing time for blurring etc. takes over a second on my laptop.

At first I thought it was the blurring process but after some investigation it turns out the vast majority of the time is due to the overhead of using PNGs.

Since there seems to be little interest in adding JPG support, I made a fork that only supports JPGs:
https://github.com/Cynary/i3lock

I would prefer to send it to i3lock directly as a PR, and I believe it can be done without adding extra hard dependencies - we can instrument make to not build the jpeg support if libjpeg is not found. I may try to polish up my diff so it can be a good PR, but it would be nice to know ahead of time if it won't just be shot down (main argument against it seems to be about adding an extra dependency - making it optional should make that argument a little moot).

**Comment by stapelberg** [comment]
Side note: we don’t do optional compilation in i3 projects. Features either work everywhere, or they don’t (modulo platform limitations, e.g. the lack of PAM on OpenBSD).

Looking at https://github.com/Cynary/i3lock/commit/f6d9f3accefd7bf62b520c2e328db00c9f0c730c, adding >500 lines of unclearly-licensed code to i3lock (aside from the extra dependency, of course) just for this feature still doesn’t seem worth it to me.

If all we needed to do is add a small handful lines of code and a dependency on a widely-available jpeg library, I’d be willing to reconsider.

**Comment by crypdick** [comment]
I have a hard time understanding why an extra- what, 10Kb?- of code is even an issue. I would gladly take the 100,000x reduction in wasted space and delete the 1GB of converted wallpaper pngs I had to make.

**Comment by stapelberg** [comment]
I’m not talking about the binary size increase in the i3lock executable at all. I’m talking about code which we have to understand and maintain. The bigger issue than the size is its license, which prevents us from incorporating it.

**Comment by Cynary** [comment]
I agree with the licensing issue - I sent an email to the developer asking about it, but I am still waiting to hear back.

In that case, though, this doesn't seem like too hard a project - adding a function to load an image from a jpeg onto a cairo surface - and likely wouldn't add too much code. If the dependency on libjpeg is considered an acceptable compromise I'll take some time to do it, and build a new PR.

**Comment by stapelberg** [comment]
I wonder why cairo doesn’t ship such code already, given that they do ship the PNG code. If someone could do some research on the cairo bug tracker and file an issue if not, that’d be great — ideally that code would live in cairo, not in i3lock.

I’m okay with adding a dependency on libjpeg.

**Comment by Cynary** [comment]
I found this exchange (in regards to the cairo_jpg library above): https://lists.cairographics.org/archives/cairo/2016-January/027139.html

It seems like cairo is of the opinion that image loading should be done outside the library, and PNG is at most a convenience they provide.

Also, from the comment on this code:
https://github.com/rahra/cairo_jpg/blob/master/src/cairo_jpg.c

>  * @license This code is free software. Do whatever you like to do with it.

and the exchange in the mailing list, seems like it should be free use for cairo_jpg. I'll reduce the dependency, though, there's a lot of extra unneeded stuff in there.

**Comment by stapelberg** [comment]
>> @license This code is free software. Do whatever you like to do with it.
>
> and the exchange in the mailing list, seems like it should be free use for cairo_jpg.

That declaration is not a proper license in the https://en.wikipedia.org/wiki/Debian_Free_Software_Guidelines sense, which will make getting that code into Linux distributions hard.

In fact, my requirement is even stricter: the code must be licensed under a BSD license, just like the rest of i3.

**Comment by psychon** [comment]
Let me just mention GdkPixbuf and walk away again...
Some GPL code (sorry!) to give you an idea on how much code might be required:
https://github.com/awesomeWM/awesome/blob/cc68ac929209c8b33c2ece662d075ab20ec1458f/draw.c#L180-L193
https://github.com/awesomeWM/awesome/blob/cc68ac929209c8b33c2ece662d075ab20ec1458f/draw.c#L84-L134

**Comment by tmccombs** [comment]
fwiw, swaylock uses GdkPixbuf as well.

**Comment by qrockz** [comment]
still no jpeg support :(
