### ISSUE TITLE
Keyboard Layout Switching

### ISSUE THREAD

**Issue by valsoray17** [i3/i3lock#69]
When i3lock is shown I cannot change the keyboard layout with configured key combination. It happens with version 2.7

**Comment by Airblader** [comment]
Well yeah, of course it won't work. It's a screen lock. If  bindings continued working, that wouldn't be much of a lock. Sorry, but this is intended.

**Comment by valsoray17** [comment]
But the binding configured via setxkbmap, it's not part of the i3 config. 

How am I supposed to change the layout with the screen locked?

**Comment by valsoray17** [comment]
Am I getting this correctly that to to fix this I need to wrap i3lock in script and change the layout to preferred one?

**Comment by Airblader** [comment]
Yeah. Also see #52

**Comment by valsoray17** [comment]
That's very unfortunate... Thanks for quick reply

**Comment by valsoray17** [comment]
As a matter of fact, the layout switching is actually works. The problem was that after entering pwd with wrong layout it wasn't cleared right away (maybe some kind of a delay).

Anyway, thanks for your input and sorry for false alarm!

**Comment by zsabay** [comment]
@valsoray17 Did you solve it? I have the same issue

**Comment by valsoray17** [comment]
Layout switching is working. The problem was in a delay after entering pwd is wrong layout an entered text was not cleared quick enough.

Try running i3lock with --debug enabled and see what happens.

**Comment by zsabay** [comment]
@valsoray17 I would like to but is there any way to unlock without a password in debug mode? Because if I run i3lock with Cyrillic layout I have no way to unlock and see the debug output only rebooting works

**Comment by valsoray17** [comment]
Go to VT2 and do 'killall i3lock'
