### ISSUE TITLE
Missing Dependency from the List

### ISSUE THREAD

**Issue by madisodr** [i3/i3lock#77]
Its not a big deal and anyone who spends 5 seconds reading the build make message will know whats missing but the list in the readme of required libraries is missing libxcb-dpms0-dev. At least this is the case for my Ubuntu 14.04 LTS box.

**Comment by stapelberg** [comment]
We actually removed DPMS support with https://github.com/i3/i3lock/commit/929e541fb78aa167fc52eb684d4fdff8b305b246, so this issue is trivially fixed already :).
