### ISSUE TITLE
[BUG] When i3bar set to "mode hide", it will be displayed over lockscreen on modifier key press

### ISSUE THREAD

**Issue by LeonardKoenig** [i3/i3lock#8]
Reproduce:
Set i3bar to

    mode hide
    hidden_state hide
    modifier $mod

On i3lock i3bar will be drawn on top of i3lock.

**Comment by stapelberg** [comment]
Can you be more specific? What does `i3lock --version` print for you? How do you invoke i3lock, and with what arguments?

Whenever its window gets obscured, i3lock raises itself into the foreground. On my machine, this works so fast, that I don’t even see i3bar showing up at all. If I add a sleep statement, I see a small flicker — is that what you mean?

**Comment by LeonardKoenig** [comment]
"i3lock: version 2.6 (2014-07-18) © 2010-2012 Michael Stapelberg"

Just figured out the issue: I use compton to set transparency on the statusbar. I don't know why this influences the visibility of the i3bar over i3lock, though.

**Comment by stapelberg** [comment]
Thanks for clarifying. We don’t support compton or any other compositing, so you’re on your own with this issue, sorry.
