### ISSUE TITLE
i3lock covered by other window and unable to receive input

### ISSUE THREAD

**Issue by cgogolin** [i3/i3lock#80]
If an application (in my case for example evolution mail when it displays a notification for an event) opens a new window while my X session is locked with i3lock, this newly created window is shown on top of i3lock and i3lock does not receive subsequent keyboard input. Consequently, my screen content is visible, which shouldn't happen while the screen is locked, and I can not unlock the screen because i3lock does not react to me entering the password.

The loss of input focus is not reproducible and only happens sometimes, but the covering can be triggered easily by executing `i3lock && sleep 10 ; evince` and waiting for 10 seconds. evince appears on top of i3lock.

I am using i3lock: version 2.7 (2015-05-20) © 2010 Michael Stapelberg from the Debian testing package.

**Comment by Airblader** [comment]
Please look at #22. Are you running a compositor and if so, can you reproduce it without it?

**Comment by cgogolin** [comment]
Yes, I am running `xcompmgr`. Without it the problem does not occur.

Sorry for not finding #22.

What is the root of the problem? Are you not getting a `XCB_VISIBILITY_NOTIFY` event with compositing or does raising the window with `xcb_configure_window` not work?

**Comment by cgogolin** [comment]
Ok, from the output of i3lock --debug it looks like the problem is that less events are received with compositing. In particular, I see 
```
[i3lock-debug] Read event of type 15
[i3lock-debug] Read event of type 22
[i3lock-debug] Unhandled event type 22
[i3lock-debug] Read event of type 15
```
when evince starts in the above example without compositing and none of the above with compositing.

**Comment by Airblader** [comment]
Yes, with a compositor we don't seem to be getting the visibility notify event anymore. I'm not really sure why not, to be honest. I'm not too familiar with compositing.

**Comment by Airblader** [comment]
It could have to do with the composite overlay window:

> 3.2 Composite Overlay Window
> 
> Version 0.3 of the protocol adds the Composite Overlay Window, which
> provides compositing managers with a surface on which to draw without
> interference. This window is always above normal windows and is always
> below the screen saver window.

**Comment by cgogolin** [comment]
Other screen savers/lockers seem to have the same problem (see for example the discussion under https://github.com/google/xsecurelock/issues/6). `xsecurelock` for example seems to have worked around it by using a different window if a compositor is present (see lines 354-373 in https://github.com/google/xsecurelock/blob/master/main.c ).
Maybe this would also be a way forward for i3lock?

**Comment by Airblader** [comment]
No, we don't want to pull in composition in i3lock and risk this. The easiest way is to just change your i3lock call to something like

````
killall compton && i3lock -n && compton -b
```

@stapelberg Agreed?

**Comment by cgogolin** [comment]
That looks like a pretty ugly hack for me, but I understand if you don't want to add any compositing related code to i3lock. But then please mention that i3lock does not work properly with compositing in the readme or some other prominent place.

**Comment by Airblader** [comment]
> But then please mention that i3lock does not work properly with compositing in the readme or some other prominent place.

I very much doubt that people would read it, but that's just my opinion. Please feel free to provide a pull request documenting this. You as an affected used probably know best where you would've expected this information. :-)

**Comment by karulont** [comment]
>Yes, with a compositor we don't seem to be getting the visibility notify event anymore. I'm not really sure why not, to be honest. I'm not too familiar with compositing.

This is probably a thing which is overlooked in the composer. The composer uses some other mechanism to get the image contents and in this case I think it should send the event itself.

DISCLAIMER: I could be wrong. It has been a while since I looked at how X11 works.

**Comment by sandsmark** [comment]
Could you test with this patch, and see if it fixes it?: https://github.com/i3/i3lock/pull/96

It fixes the notifications issue at least.
