### ISSUE TITLE
scale background image

### ISSUE THREAD

**Issue by baracoder** [i3/i3lock#81]
it should be possible to scale the background image to the size of the screen

**Comment by stapelberg** [comment]
No, i3lock’s image processing support is intentionally kept minimal. Please scale your image with a different tool.

See also #31, #68

**Comment by shreve** [comment]
For future googlers, get Imagemagick and use the convert tool:

```
convert -scale 2560x1440 source-image.jpg lockscreen.png
```

**Comment by Aeres-u99** [comment]
And in case, future googlers don't know to what dimension they should  resize their image then use:
`xdpyinfo  | grep dimensions`

**Comment by ha7ilm** [comment]
Combine these two to resize image so that it fits horizontal size:

    convert -resize $(xdpyinfo | grep dimensions | cut -d\  -f7 | cut -dx -f1) source-image.jpg lockscreen.png

**Comment by neruthes** [comment]
Script for dynamically choosing the current resolution before each i3lock execution:

```sh
SCREEN_RESOLUTION="$(xdpyinfo | grep dimensions | cut -d' ' -f7)"
BGCOLOR="0,0,0"
convert "/path/to/image.png" -gravity Center -background $BGCOLOR -extent "$SCREEN_RESOLUTION" RGB:- | i3lock --raw "$SCREEN_RESOLUTION":rgb -c 00ff33 -i /dev/stdin
```

**Comment by huwqchn** [comment]
You are all heros!!!!

**Comment by lytex** [comment]
Script for selecting a random image from a set of images and use it as the background image

Write the following script into `$HOME/.local/bin/i3lock-cycle`:
```bash
#!/bin/bash

SCREEN_RESOLUTION="$(xdpyinfo | grep dimensions | cut -d' ' -f7)"
BGCOLOR="#000000"
images=($(ls /usr/share/wallpapers/*/contents/images/2560x1600*.png
    ls /usr/share/wallpapers/*/contents/images/3840x2160*.png
    ls /usr/share/wallpapers/*/contents/images/5120x2880*.png
    ls /usr/share/wallpapers/*/contents/images/3200x2000*.png))
convert "${images[ $RANDOM % ${#images[@]} ]}" -gravity Center -background \
 $BGCOLOR -extent "$SCREEN_RESOLUTION" RGB:- \
 | i3lock --raw "$SCREEN_RESOLUTION":rgb -c $BGCOLOR -i /dev/stdin
```

Make it executable:

```bash
chmod +x $HOME/.local/bin/i3lock-cycle
```

To bind it to Win+L:
```
bindsym --release Mod4+l exec --no-startup-id $HOME/.local/bin/i3lock-cycle
