### ISSUE TITLE
Always display the unlock indicator

### ISSUE THREAD

**Issue by wiltonsr** [i3/i3lock#91]
It would be nice if the unlock indicator always be displayed, regardless of the state.
(Currently it is only shown after initial keypress)

**Comment by stapelberg** [comment]
What’s the motivation for having it displayed permanently? When you didn’t press any keys yet, there’s nothing to make you aware of, is there?

It seems like the request is merely for personal preference, and we generally don’t change i3 merely for subjective preferences (as they tend to be slightly different for everybody). Closing this request for now — please let me know in case there’s a good reason to change behavior other than preference.
