### ISSUE TITLE
i3lock crashes and unlocks screen !

### ISSUE THREAD

**Issue by ismboedev** [i3/i3lock#95]
# What happens  
When i am running a virtual machine in VirtualBox, and lock the screen,
while VirtualBox is focussed (eg. with keyboard shortcut), i3lock locks the screen,
but when trying to input the password, i3lock crashes.  

# i3lock infos  
i3lock version:
`i3lock: version 2.8 (2016-06-04) © 2010 Michael Stapelberg`

i3lock debug output:
```
[i3lock-debug] device = 3
[i3lock-debug] found Xinerama screen: 1600 x 900 at 0 x 0
[i3lock-debug] scaling_factor is 1, physical diameter is 190 px
[i3lock-debug] Watching window 0x04200003
[i3lock-debug] Read event of type 15
[i3lock-debug] Read event of type 15
i3lock: Cannot grab pointer/keyboard
[i3lock-debug] Read event of type 18
[i3lock-debug] UnmapNotify for 0x04200003
```

# GIF
As soon as press a key, i3lock crashes. You can see my system info as well.  

![output2](https://cloud.githubusercontent.com/assets/18635814/18800167/cef61efe-81db-11e6-9d33-176c3c25380b.gif)

**Comment by Airblader** [comment]
The log states the problem:

> i3lock: Cannot grab pointer/keyboard

It's a fundamental problem in X that if another application has grabbed the pointer or keyboard, i3lock cannot do it. We've already made some improvements to make this clearer to the user, in particular #88 is going to make this much clearer to the user and avoid that they think it's already locked.

**Comment by justinsteven** [comment]
I realise this issue is closed, but I've found a workaround that might help others.

You can use `xdotool` to grab the name of the focused window, and if it is VirtualBox, use `xdotool` to send the VirtualBox "Host Key". This causes VirtualBox to lose focus, and i3lock can grab the pointer/keyboard.

```
sleep 5
xdotool getwindowfocus getwindowname | grep -q -- '- Oracle VM VirtualBox' \
  && xdotool key Control_R
i3lock
```
