### ISSUE TITLE
i3lock sometimes kills the i3 session

### ISSUE THREAD

**Issue by japhir** [i3/i3lock#97]
I find this issue very hard to reproduce since I don't know which commands to run for log information, that's why this issue is a bit vague. Sorry about that.

I'm using i3 version 4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors with i3lock: version 2.8 (2016-06-04) © 2010 Michael Stapelberg.

When I run the following lock script, sometimes my entire x session is shut down and I'm back at my LightDM login screen, with all the x processes killed:

```
#!/bin/bash
scrot /tmp/screen_locked.png
convert /tmp/screen_locked.png -scale 10% -scale 1000% /tmp/screen_locked2.png
i3lock -i /tmp/screen_locked2.png
```

which I invoke with the following shortcut from my [i3config](https://github.com/japhir/ArchConfigs/blob/master/Laptop/i3config) (second part commented out):

```
bindsym $mod+Delete exec ~/ArchConfigs/launchi3lock.sh # && sudo sh -c "echo mem > /sys/power/state 
```

At first I thought this only happened when I was running a virtual machine with VMWare (Windows 10), but just found out it also happens when just running chromium, a terminal and emacsclient.

Could you offer any ideas on how to debug this issue?

**Comment by stapelberg** [comment]
Check your X server’s logfile for crash messages. You should be able to find it in /var/log/Xorg.0.log.old (precise path might vary by distribution).

If you can reproduce the issue with a reasonable success rate, you might want to try testing a different driver (vesa? modeset?) and see if the issue still happens.

**Comment by japhir** [comment]
I don't see any error messages in my logs (both [/var/log/Xorg.0.log.old](https://www.dropbox.com/s/mbru3bvqbvlmr99/Xorg.0.log.old?dl=0) and [/var/log/Xorg.0.log](https://www.dropbox.com/s/9gtm3m0h70750dr/Xorg.0.log?dl=0)). The crash just happened before I logged in, opened a terminal and copied the log files to dropbox.

**Comment by stapelberg** [comment]
> It might have something to do with me using a dual head with bumblebee so I use both the mesa and the nvidia drivers.

nit: your logfile actually says you’re using the intel driver, not the mesa driver.

Which display manager are you using (e.g. gdm, lightdm, …)? Can you check the logs of your display manager as well please? The display manager will realize when the X server exited, so it should at least tell you the exit code, and maybe even an error message.

Checking the journal might also be a good idea: `journalctl -b`

**Comment by mherzberg** [comment]
I have the same issue on two different machines (Desktop and Notebook, both Intel integrated graphics using gdm as the display manager). The error happens roughly once every few days.

The first line in my error logs is always:
```/usr/lib/gdm/gdm-x-session[605]: Xorg: present.c:489: present_flip_notify: Assertion `vblank == screen_priv->flip_pending' failed.```

This line is followed by lots of different errors by various applications, which all seem related to them not finding the X server anymore.

**Comment by japhir** [comment]
I use lightdm, its log says the following:

    [+10430.55s] DEBUG: Greeter requests session i3
    [+10430.55s] DEBUG: Seat seat0: Stopping greeter; display server will be re-used for user session
    [+10430.55s] DEBUG: Session pid=11628: Sending SIGTERM
    [+10430.55s] DEBUG: Greeter closed communication channel
    [+10430.55s] DEBUG: Session pid=11628: Exited with return value 0
    [+10430.55s] DEBUG: Seat seat0: Session stopped
    [+10430.55s] DEBUG: Seat seat0: Greeter stopped, running session
    [+10430.55s] DEBUG: Registering session with bus path /org/freedesktop/DisplayManager/Session1
    [+10430.55s] DEBUG: Session pid=11672: Running command /etc/lightdm/Xsession i3
    [+10430.55s] DEBUG: Creating shared data directory /var/lib/lightdm-data/japhir
    [+10430.55s] DEBUG: Session pid=11672: Logging to .xsession-errors
    [+10430.60s] DEBUG: Activating VT 7
    [+10430.60s] DEBUG: Activating login1 session c4
    [+10430.61s] DEBUG: Seat seat0 changes active session to 

the `.xsession-errors` file doesn't show anything pertinent. I couldn't figure out where and if Compton writes its log files.

**Comment by mherzberg** [comment]
Possibly related to https://bugzilla.redhat.com/show_bug.cgi?id=1333486

**Comment by Airblader** [comment]
A coworker has seen a similar issue where sometimes i3lock crashes the entire X session. The logs revealed that nouveau is killing X, so we assume it's a problem there. We've switched him to the proprietary drivers for now and the issue hasn't occurred again to my knowledge.

**Comment by japhir** [comment]
Forgot to close the issue. Hadn't bothered me since switching to proprietary drivers. Thanks!
